### ISSUE TITLE
no www certificate?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1020]
It seems our certificate is only valid for "cantusdatabase.org": adding a www leads to a warning. I think we want the address to be valid with or without the www (we reference it both ways in different places).
<img width="840" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/1f1496f5-54dd-485b-a7c9-a259bdd115bf">

**Comment by jacobdgm** [comment]
I've done a bit of poking around, and I can't immediately find a solution to this. @kqct, when you have a chance, do you have any insights into how we could fix this?

**Comment by jacobdgm** [comment]
update: I manually ran a command, and `www.cantusdatabase.org` is now certified as it should be. #1035 should make this permanent.

(it's worth noting that the cron job to update the certificates is not working, but we have a separate and distinct issue for that: #1036. But it will be fine if this issue gets closed by #1035 getting merged, since #1036 is open.)
