### ISSUE TITLE
json-cid API might not be working as expected

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1092]
We got an email from Jan in the wee hours of this morning:

> Hi again, based on my very fast exploration, the problem might be on the new CD server (not under my maintenance).
> 
> Export for Cantus ID ah54180 works well on the old CD site:
> https://cantus.uwaterloo.ca/json-cid/ah54180
> On the new CD it gives an empty array.
> https://cantusdatabase.org/json-cid/ah54180
> Not all the new CD exports are affected by this bug. For example, this works well:
> https://cantusdatabase.org/json-cid/001234 (my favorite Cantus ID number)

The subject line from the email was "disappearing entries" - the series of replies seems to have been cut off, but the sense I get is that some records from CantusDB are not showing up among the concordances around the Cantus Network.

**Comment by annamorphism** [comment]
There seem to be two things going on here:
1. It used to be the case that unpublished Cantus sources still showed up in concordances on CantusIndex, whereas now they are hidden. People are reacting to this as "I am not seeing as much as I used to." This is by design, but we should still check whether this filtering happens on the CDB end or the CI end. 
-->We could ignore this problem, OR there could be a compromise where unpublished sources are shown but not linked--but most of this would probably have to happen at the CI end if we chose to pursue it.  (Consequences for us would be cleaning up test sources with dummy chants).

3. There is a problem with the BowerDB sources. In the cases Jan highlighted, the export used to include the concordances with the Bower Database, but now only includes /chants (which means in some cases it is empty.) It also means that some chant IDs, e.g. ah54007, have different concordances on their /sequence pages (which provide only Bower concordances) vs their /chant pages (which provide concordances with everything BUT Bower.)
-->One possible solution here would be to treat the Bower database as its own mini-database, so that concordances show up as "30 from Cantus Database, 25 from MMMO, 45 from Bower" or whatever. To confirm with Debra if this is the correct approach.

**Comment by jacobdgm** [comment]
also, putting a thing here that came up while Anna and I were looking at this.

Currently, on Sequence Detail pages, we only display concordances from within the Bower Database, presented somewhat differently. In a perfect world, sequences from BowerDB would show up in the main concordances list on Cantus Network sites, and we could use the same concordances display on Sequence Detail pages that we use on our Chant Detail pages.

**Comment by jacobdgm** [comment]
I'm fairly confident this is a Sequence thing (i.e., all the ah54007 chants are actually Sequence objects, and we list only Chants and no Sequences in this API). @annamorphism, do you want to email Debra to ask about whether sequences should be included in Concordances? Should I? **Or should we just add them because they're present in OldCantus?**

**Comment by annamorphism** [comment]
I will discuss this with Debra--either this week in person, or (more likely) on Monday through email. 
My feeling is that I think we should have something, because OldCantus did, but I'm not sure if that is best done by including both Chants and Sequences (as the old version did) or by distinguishing between the two.

**Comment by annamorphism** [comment]
Hang on--I don't think we would want the same concordances on Sequence Detail pages, would we? The inside-Bower concordances includes "Notes" and "Rubrics" that wouldn't display in that case. Unless we had a "concordances inside Bower" table in addition to the regular concordance table?

**Comment by jacobdgm** [comment]
> Hang on--I don't think we would want the same concordances on Sequence Detail pages, would we? The inside-Bower concordances includes "Notes" and "Rubrics" that wouldn't display in that case. Unless we had a "concordances inside Bower" table in addition to the regular concordance table?

Right - I don't understand why Notes and Rubrics are included in the Concordances table on Sequence Detail pages on OldCantus.
- Is it because it's important that this information be shown for sequences?
- Is it because there was a technical restriction preventing the main Concordances table from being displayed, so when the Sequences Concordances table was being put together, Notes and Rubrics were bits of information that were available, so why not include them?

If it's the former, then I don't understand why sequences from the Clavis Sequentiarum should ever show up in the main concordances table at all.

**Comment by annamorphism** [comment]
> Right - I don't understand why Notes and Rubrics are included in the Concordances table on Sequence Detail pages on OldCantus.

I can't answer for Notes (which are frankly a bit mystifying), but the Rubrics include similar (but not identical) information as the Feast field for chant objects. It's not presented in the same way, but it lets people see different usages at a glance. If one replaced this table with the standard Concordance table you'd either have to replace this with a blank Feast column, or shoehorn them into the Feast field (which it doesn't quite fit.) Possibly having both a Bower-only and an all-network table would address this?

> If it's the former, then I don't understand why sequences from the Clavis Sequentiarum should ever show up in the main concordances table at all.

But we have some IDs (e.g. ah54007) that exist in both, so not including the Bower ones suggests we don't know about some instances that in fact we do know about. Maybe this is fine (we also know about unpublished chants without revealing them) but it is a change from what was done previously. I've presented the issue to Debra and will report back .

**Comment by jacobdgm** [comment]
I'm going to make an executive decision and say that no action is required here - we're not sharing information about unpublished chants, we're not sharing information about objects in the Bower segment (which is, in a sense, also unpublished), and all the published Cantus-segment information is being shared as it should.

I don't think CI is going to be making use of this endpoint now that we have our One True API with all the concordances, and last I heard from Jan is that the One True API looks good. Going to close this; we can reopen if it ever becomes apparent that we need to make any changes on our end.
