### ISSUE TITLE
We need to test all/many paths on OldCantus to check that a page can be found at that path on NewCantus

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1096]
Before too long, OldCantus will be shut down. The plan is that the web administrator at the University of Waterloo, where OldCantus is hosted, will set up a redirect at cantus.uwaterloo.ca/{path}, which will redirect to cantusdatabase.org/{path}.

Before this redirect is set up, we should find a way to systematically test all valid paths on OldCantus, and ensure that the path is also valid in NewCantus.

**Comment by jacobdgm** [comment]
@zhannaklimanova, would it be possible to create a crawler that compiles a list of all pages on cantus.uwaterloo.ca, so we can make 100% certain we haven't missed anything?

Presently, I will take a look at the OldCantus source code to see if I can find a list of paths that we can look at to ensure that nothing unfamiliar appears there.

**Comment by jacobdgm** [comment]
I've checked the source code, and I can't make any sense of it. ChatGPT suggests that paths in a drupal project should be found in `*.routing.yml` files; I've checked all the `.yml` files in the source code, and none contain anything resembling a list of paths.

Based on the little I know about Drupal, I'm guessing that routing was specified somewhere in the database, and not in the source code.

Hoping @zhannaklimanova might be able to come through with a crawler. I'm already highly confident (>95%, say) that we haven't missed any pages that CantusDB users actually use, and I'm not sure what we can do at this point to push this to 99% or 99.9%.

**Comment by dchiller** [comment]
I'm also wondering if there exists a sitemap that Jan could provide.

**Comment by zhannaklimanova** [comment]
Yes, I will take a look at this.

**Comment by dchiller** [comment]
@jacobdgm What was the google tool that you were using to work with Google analytics? I have been doing some googling to try to figure out how we might do this, and I'm seeing some possibilities involving "Google Search Console". I'm wondering if this is what you were already in to deal with the analytics business?

Also, just putting this here in case we decide to write our own: https://scrapy.org/

**Comment by jacobdgm** [comment]
Hm... When I navigate to to analytics.google.com or to search.google.com/search-console, I'm brought to pages showing data about Cantus Database. Several months ago, @ahankinson helped set this up so my google account was able to access this data.

This brings up an important side point - I'm pretty sure I'm the only person in the lab with access to this. Ideally, @dchiller and/or @lucasmarchd01 is given access as well (and I'd be happy to stop receiving emails about search result rankings for CantusDB once my contract runs out). @ahankinson, is this something you would be able to facilitate?

**Comment by ahankinson** [comment]
Sure, send me an e-mail with the details of who should be added, and their preferred e-mail address for accessing Google stuff.

**Comment by dchiller** [comment]
Ok, I'm doing some crawling of OldCantus in between other things. At the moment, there are two categories of url's that I am finding that are on OldCantus and not NewCantus:

1. `/next-chants/no-js/[source_id]/[folio]`. For example, see [this link on OldCantus](https://cantus.uwaterloo.ca/next-chants/no-js/123714/215v) and [the same path on NewCantus](https://cantusdatabase.org/next-chants/no-js/123714/215v). I  don't think we need to worry about these cases, because I think this would only be used internally... does that seem correct? On OldCantus, it seems to be used for the link to the previous and next folios' chants on the sidebar of the chant detail page:
![image](https://github.com/DDMAL/CantusDB/assets/11023634/eeffe020-eb9f-4115-af43-20c8f378ea6a)
NOTE: The same thing happens with `/previous-chants/no-js/[source_id]/folio`.

2. `/display-concordances/[chant_id]`. For example, see [this link on OldCantus](https://cantus.uwaterloo.ca/display-concordances/182348) and [the same path on NewCantus](https://cantusdatabase.org/display-concordances/182348). It again, seems to be used for a link on the Chant Detail page, this time as the url behind the "Display concordances" button. Like 1, we've gotten rid of this in the CantusDB set-up and I can't imagine it being necessary to recreate for any external audience. 

That's it for now! Will comment again if I find other things.

**Comment by dchiller** [comment]
I found no other issues in my crawler and the redirects have been up for about a month now with no major issues (#1441 was the only related issue that has been found in that time). Going to close, and we can reopen if any other specific errors emerge.
