### ISSUE TITLE
CI Search View: we should remove link to email Jan

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1124]
![Screenshot 2023-11-02 at 4 14 44 PM](https://github.com/DDMAL/CantusDB/assets/58090591/8b4f6d4e-c45d-4ad2-a348-99750eb874cf)
^ this was with me mousing over the "administrator" link

**Comment by annamorphism** [comment]
this text should be fixed anyway. Most people who are using this tool don't have the authority to add a chant into Cantus Index, in which case they should be emailing a Debra to do it for them. If it's not showing up because of some bug, then a current developer needs to know, but probably a Debra should first make sure it really is a bug and not a typo in standard spelling (which is usually what it is.) 
So the message should be changed to e.g. "Please check that you are using standard spelling; if you believe the chant needs to be added to Cantus Index, contact [Debra]". Or some such.

**Comment by jacobdgm** [comment]
Linking #1171 - the CI Search View currently doesn't exist. When we re-implement it, it will not be difficult to not include Jan's address. Closing.
