### ISSUE TITLE
global search bar - we should tweak policy for when it searches for Cantus IDs vs. for incipits

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1138]
While looking into #1136, I tried to search for `isti sunt sancti*` in the search bar. Upon pressing enter, I got no results:

![Screenshot 2023-11-07 at 4 19 21 PM](https://github.com/DDMAL/CantusDB/assets/58090591/e219d932-08a9-4732-8c25-a872383c2588)

It seems that, since the search term contains a `*`, i.e., a non-letter character, CantusDB assumed I meant to search for a Cantus ID.

We should revisit the logic for deciding whether to display results by Cantus ID vs. by incipit - the deciding factor should probably be whether it contains a numeral, rather than whether it is only alphabetic.

**Comment by annamorphism** [comment]
Agreed! I think I ran across this for something similar (quotation marks maybe?). I think we can expect that all searches for cantusIDs will contain a numeral, and no searches for incipits will, so that seems like a good criterion (unless there is some "Ist1 sun7 sanc71" in the database somewhere...
