### ISSUE TITLE
We should create a hook that updates a chant/sequence's `incipit` field when the chant/sequence is saved

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1187]
We don't keep chants' `incipit`s up-to-date, yet `ajax_search_bar` searches the `incipit` field. So, as users add chants, they will not appear in search results while the user is typing in the search bar.

In general, we need to do something with incipits: either update them based on some rule in `signals.py`, or calculate them on-the-fly. See #361, and perhaps one or two other issues. Recent times we've met with her, Debra has mentioned wanting to have a consistent way to handle incipits.

**Comment by annamorphism** [comment]
I thought the consensus was to create an incipit off the full text of each chant (when present), so that it is consistent with whatever the fulltext is. I suppose this would be a bit like the best-text-for-syllabification, in that when there is no fulltext one would keep the current incipit value, to be replaced if the full text is ever added.

**Comment by jacobdgm** [comment]
Right - we've got to keep the `incipit` field around, because some chants have only an incipit and no full text. So it seems that we need to automatically update the `incipit` field, almost certainly with a hook/signal whenever a chant/sequence is created/modified.

We'll only ever want to use the Standardized Spelling fulltext, correct @annamorphism, and never the MS Spelling fulltext?
