### ISSUE TITLE
`?` link under "Office" on Chant Create page leads to `404`

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1203]
To reproduce: 

- Go to Chant Create page
- Click on the question mark link underneath the Office field: 
<img width="478" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/161b5681-3365-4c11-b727-13dfe3f74b02">
- Get `404`

**Comment by jacobdgm** [comment]
ah, the path for this page is now `/description` rather than `/field-description` - this is an easy fix.

(Update: the following point is actually already set up) We'll also need to add `id` attributes to each of the `<p>` tags on the `/description` page, so we can link to `/description#Office`. This is another easy fix.
