### ISSUE TITLE
json-nextchants

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#123]
OldCantus has a json-nextchants function/API, which we may want to implement.

it appears to:
- take in a Cantus ID, and return a JSON object / dictionary.
     - e.g. https://cantus.uwaterloo.ca/json-nextchants/003828
- each key in the dictionary appears to be the Cantus ID of another chant. each value is (i assume) the number of times that the second chant appears immediately after the first chant among all manuscripts.

In an email, Debra Lacoste commented that "THIS LOOKS TO BE THE ONE IN THE DATA-ENTRY SCREEN THAT SUGGESTS THE NEXT CHANT TO THE INDEXER."

**Comment by annamorphism** [comment]
just confirming that is indeed what this is doing, and it's quite handy. here is what it looks like to somebody entering a chant: 
![image](https://user-images.githubusercontent.com/67451875/171231993-67e09c25-cc2f-4e56-b4ba-4cdc3687f75a.png)
the chants are also ordered from most common to least common.

**Comment by jwang44** [comment]
Yes. This is on the "chant-create" page. We call it "the suggestion tool". We already have an implementation for this in the `ChantCreateView` but it is nowhere near elegant or efficient. It would be good to revisit it now that we  have the "ground-truth" results from the old Cantus. 

The content of the JSON export are exactly the context variables we need for the suggestion tool on the chant-create page. So here's what we need to do:
1. Improve the code for the suggestion tool and make sure the results match what's given in the old Cantus JSON export. 
2. Use the same logic to construct a `JSONResponse`, so that we can have a view for this `json-nextchants` API on the new Cantus.

**Comment by jacobdgm** [comment]
I forgot to include a "fixes" on https://github.com/DDMAL/CantusDB/pull/130 . This should be closed now, yes?
