### ISSUE TITLE
`/index` pages take a long time to load and sometimes stall

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#1238]
See, for example, https://cantusdatabase.org/index/?source=123627.

Users, including Debra, have experienced long load times and stalled rendering of the full index.

**Comment by jacobdgm** [comment]
hm... opening this myself several times, load times for the page are always ~2s. Not sure whether the ComputeCanada VM was having a bad day or something that day, but in any case, it would be better if the page loaded faster than it does.

Maybe this is a place to experiment with asynchronous loading - we could load chants in batches and display them once they've loaded, and display a loading icon while waiting for the first batch to be fetched.

**Comment by dchiller** [comment]
FYI, it took 13s for me just now...

**Comment by ahankinson** [comment]
I've found really sketchy loading times with Compute Canada, particularly with Ubuntu. I've been in touch with them and they basically said "it's working fine." There *may* be an issue with the type of virtual HD device driver they're using?

I've switched to Fedora for our experimental Linked Data machine on the allocation, since it seems to make a difference. I've switched to FreeBSD for DIAMM, and the difference is night-and-day, but again, I don't know why.

So YMMV, but I'm suspecting possibly a weird configuration interaction between Ubuntu and the OpenStack Volumes.

**Comment by dchiller** [comment]
Interesting...so we may wait on doing more with this until we've done the CantusDB OS update...

**Comment by ahankinson** [comment]
It's anecdotal, but for SFTP uploads of DIAMM images on Ubuntu, we were generally seeing ~2-300kbps. Switching to FreeBSD, we're seeing ~5-8mbps. The only thing that changed is the underlying OS / Filesystem. (Data centers or upload locations stayed the same; it's still using an OpenStack Cinder Volume on Arbutus.)
