### ISSUE TITLE
json-analysis-export

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#124]
OldCantus has a json-analysis-export tool/API that we may want to implement.

- looking at the source code, it seems to accept as arguments either a node ID or a source.
- tried accessing https://cantus.uwaterloo.ca/json-analysis-export/002622 (with the cantus ID of a chant), https://cantus.uwaterloo.ca/json-analysis-export/250245 (with the ID of a chant), and https://cantus.uwaterloo.ca/json-analysis-export/ (without any suffix), and all turn up blank pages.
- tried accessing https://cantus.uwaterloo.ca/json-analysis-export/123591 (with the ID of a source), and it turns up a blank page. Sources, I believe, don't have Cantus IDs

In an email, Debra Lacoste commented that "IT MIGHT HAVE SOMETHING TO DO WITH THIS: http://cantusindex.org/analyse ... THE ANALYSIS TOOL ON CANTUS INDEX IS FOR FEASTS"

**Comment by annamorphism** [comment]
It works if you include ?src= before the source ID--that matches the link for "update in the Cantus Analysis Tool" 
![image](https://user-images.githubusercontent.com/67451875/171228337-e8af0c4e-2584-4e1f-a563-d37f0f644afd.png)

I don't really know how (or why) it would work for a  single chant ID, but if it did it would probably be as a node rather than a Cantus ID, since the analysis tool compares chants and feasts across sources.

**Comment by jacobdgm** [comment]
closing this for the time being - we can re-open it if/when someone complains.
