### ISSUE TITLE
redirect mass.cantusdatabase.org?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1255]
In #1095 it was mentioned that Google was indexing mass.cantusdatabase.org. Today while searching something I was in fact sent to https://mass.cantusdatabase.org/source/124088, which gives me an error about not connecting to the server. Deleting "mass" takes me to what is, I assume, the intended result--should this be a redirect, so people can get there despite google giving them a bum steer?

**Comment by dchiller** [comment]
Just to confirm @annamorphism when you were "searching for something" this search was on Google? 

In any case, yes, we should (and will) redirect anything that has the `mass.cantusdatabase.org` domain to `cantusdatabase.org`

**Comment by jacobdgm** [comment]
re-opening this because while the PR has been merged, more work remains to be done.

Current state of affairs: We created a new DNS record for mass.cantusdatabase.org, pointing to the same IP address as cantusdatabase.org.

Tomorrow, we hope to either merge staging into production, to incorporate changes that allow Nginx to redirect traffic from mass.cantusdatabase.org to cantusdatabase.org, or to simply apply a hotfix to production setting up this redirection. When we do this, we will also have to request new certificates for the mass subdomain.

Until we request the new certificates, people coming across pages at the mass subdomain will be shown a warning page saying the certificates are not valid.

We did this so that we will not need to ask Debra to help us log into her hover account again tomorrow.

**Comment by ahankinson** [comment]
A couple things:
 - you might want to consider whether its worth it. I'm generally all for redirects, but given that it was published by mistake and wasn't official to start with, doing all this work has the paradoxical effect of actually making it official (an actual domain, a server setup, and a certificate.)
 - the google results will actually disappear once the indexing catches up with the new setup., so this is not  a permanent problem.

**Comment by jacobdgm** [comment]
These are valid points, @ahankinson. But @dchiller and I set this up with a 301 Moved Permanently earlier today.

We know about this causing problems for Google results. But since these pages have been appearing among search results for years, it's possible - likely even - that at least one person has added some of these pages to their bookmarks, linked to them, etc.. We don't know about the scope of this latter problem.

In any case, whether or not setting up this redirect was worth it, it's done now. Closing.
