### ISSUE TITLE
Browse Chants page: we must fix "Source" dropdown behavior

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1336]
Browse chants has a dropdown of shelfmarks that always shows A-Gu 29; seems like this should show the current source...
e.g. https://cantusdatabase.org/source/714555/chants/

<img width="525" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/757da611-7ebc-45d5-93cd-dec3e9dcc062">

**Comment by jacobdgm** [comment]
huh. And if you select, say, **A-Gu 30** (source 123611) from the dropdown, instead of getting sent to `/source/123611/chants`, you get sent to `/source/714555/chants?source=123611&feast=etc.etc.etc`, and you see the same set of 13 chants from **US-RiCTpc D-0yp1h**. This isn't the expected behavior at all!

**Comment by jacobdgm** [comment]
The way we have the URIs set up now, we're looking at the `source/` with id `714555/` and specifically the `chants` contained within it, so conceptually it's a bit odd (to me) that you should be able to select a different source from the first dropdown and hop to `source/<another-id>/chants`.

I'm curious whether any users are currently navigating around the site in this way. I think the cleanest solution would be to get rid of the "Source" dropdown (since based on the URI, this page is meant to pertain to one specific source), but we have to assume that some users actually use this dropdown and will miss it if we remove it. So the current source should be selected upon page load, and selecting a new source from this dropdown should bring users to the page at `source/<another-id>/chants`.

**Comment by annamorphism** [comment]
I agree that the cleanest thing would be to get rid of it, though of course I don't speak for all users! It looks like OldCantus had this set up as /chants?source=blah, for which the selection mechanism makes more sense--I can't say I ever myself went about getting the site to "show me the subset of all chants that happen to belong to this particular source", but in principle you could browse chants in this way (which on NewCantus you cannot). But I don't think anything ever linked to the main "browse" page, so the navigation is a bit gunky (was it not fully implemented? or was it removed, and the existence of these dropdowns is a bit of it that remained, kind of like the old "proofread" pages?)
