### ISSUE TITLE
We need to reimplement the CI Search View 

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1391]
This feature was turned off by https://github.com/DDMAL/CantusDB/pull/1142, and we need to turn it back on again.

https://github.com/DDMAL/CantusDB/commit/7b18c99a911bb0aac88886842af1ef011d1c6359 was the commit responsible for removing this functionality (https://github.com/DDMAL/CantusDB/commit/49a1978e20d65d06aacf407573dc3f2b1ce7789e could also be useful for writing tests for this view).

It occurs to me that I'm not aware of any CI endpoint that is directly helpful for turning this feature on. Previously, we had made a request to the page at https://cantusindex.org/search and parsed the HTML it returned; hopefully there's a better way to implement this feature. It might be worth asking Jan about how OldCantus did this.

**Comment by jacobdgm** [comment]
Assigning this a priority of "high" - this is a feature that OldCantus had that we don't currently have.

**Comment by annamorphism** [comment]
assuming this is indeed the so-called Input Tool, we've actually had some people *other* than me and Debra request this one. So somebody should be assigned to it!

**Comment by jacobdgm** [comment]
Cantus Index Search View is the internal name we give the view referred to as the "Input Tool" on the front-end. So yes, they're equivalent.

Copying something I left on #1410, this issue's doppelganger:

> Leaving a note here that whenever this gets reimplemented, I would recommend that we not simply recreate what we had pre-bytespider-incident - the previous implementation involved requesting the CI search page, parsing the HTML to grab certain values from the table CI returned, and then displaying a list of results based on the data we'd scraped. To say the least, this was a brittle implementation.
> 
> Unfortunately, I'm not aware of any API Cantus Index provides that would allow us to request the information we need. It may be worth emailing Jan to ask how this was implemented in OldCantus, and whether he could create an API that would allow us to request a list of chant texts directly.

Someone who will be working on CantusDB into the future should strongly consider contacting Jan!

**Comment by dchiller** [comment]
I've emailed Jan about the possibility of having the `json-text` API on Cantus Index working on cantusindex.uwaterloo.ca so that we can use it for this feature. He says it is in the queue.

I would suggest that we put this issue "on hold" until that is completed.

**Comment by annamorphism** [comment]
since this is already high-priority-special-request-all-caps I can't do much to bump it, but I continue to get requests for this feature's return. possibly optimizing the "next chant suggestions" as in #1424 would be a stopgap, if there is no possibility of progress before things happen on Cantus Index's end.

**Comment by dchiller** [comment]
> possibly optimizing the "next chant suggestions" as in #1424 would be a stopgap

The optimizing referenced there is about speed, no? Which doesn't really seem like it would help here...

I guess we could just use the old Cantus Index for this and the new Cantus Index for the other features? I seem to remember discussing that in some context with @lucasmarchd01 but can't remember if/where/why we landed. Thoughts?

**Comment by annamorphism** [comment]
> > possibly optimizing the "next chant suggestions" as in #1424 would be a stopgap
> 
> The optimizing referenced there is about speed, no? Which doesn't really seem like it would help here...
> 
True--but if this feature were saving people more time, the extra time invested in having to go look up other chants not suggested would be less of a slowdown, I guess. 

> I guess we could just use the old Cantus Index for this and the new Cantus Index for the other features? I seem to remember discussing that in some context with @lucasmarchd01 but can't remember if/where/why we landed. Thoughts?

As far as I'm concerned that sounds good!

**Comment by lucasmarchd01** [comment]
> I guess we could just use the old Cantus Index for this and the new Cantus Index for the other features? I seem to remember discussing that in some context with @lucasmarchd01 but can't remember if/where/why we landed. Thoughts?

Okay, let's go ahead and implement it this way for now!

**Comment by lucasmarchd01** [comment]
Something I noticed while re-implementing this feature using the `json-text` API instead of the `search` API:

1. A search using https://cantusindex.org/search?t=alleluia&cid=&genre=All will result in **4916** chants. In the previous implementation we would parse the HTML returned from this search from the first **5** pages (or 500 chants) of the table to return to the user on the CISearchView.
2. A search using https://cantusindex.org//json-text/alleluia will result in **50** chants. I think no matter what search you make, the maximum number of results it will return is 50. Using our new implementation with this API, we display up to all 50 of these results to the user, but this is significantly less than before.

Will this be a problem? We have a message on the CISearchView that says "If your chant is not included here, please add it into Cantus Index or contact the administrator" so I can imagine in some cases when a user doesn't find their chant they will be confused.

We can change this message to something like "Please note that the search results are limited to the first 50 chants. ..."

**Comment by dchiller** [comment]
Hmm...this is odd...it does seem like 50 must be a default amount. I wonder if there is a way to change that limit with a query parameter. Perhaps we should ask Jan?
