### ISSUE TITLE
Global search bar default behaviour

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#1493]
While working on #1089, I also noticed that when a user makes an incipit search using the global search bar, it defaults to a "starts with" operation, unlike the chant search page's keyword option, which defaults to "contains." Is this what we want?

**Comment by annamorphism** [comment]
I have a feeling this was by design (there might be an issue about it somewhere?), because people searching incipits in the first place are probably thinking about starting words.  But you're right that it's a bit displeasing to have it work two different ways in different places, so probably good to check in if this is correctly anticipating user behaviour.

**Comment by dchiller** [comment]
It looks like #903 is relevant to this. There was "a conscious decision" to search from the beginning of the text for the chant search page that you get to by using the search bar. I have yet to find any reference to why that "conscious decision" was made.

**Comment by annamorphism** [comment]
possibly I'm thinking of the discussion in #519 about starts-with...

**Comment by annamorphism** [comment]
I think this behaviour is also expected because of the prompt to enter an incipit or Cantus ID; if I see "enter an incipit" and write "Aspiciens a longe", I'm probably expecting the ~80 "Aspiciens a longe" responsories (006129), and not the additional ~40 chants that happen to have those words in them but a totally different incipit, like "Doctor bonus et amicus dei" (006484).  If it said "enter words anywhere in chant" then I might expect to default to "contains."

**Comment by dchiller** [comment]
I could definitely see a different approach to the global search bar (that it would be a `contains` search, possibly with a heavier weighting given to text in the incipit), but agree that the current display (calling it an "incipit" search) suggests that it should be starts_with
