### ISSUE TITLE
Create an Institutions Model

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1505]
An "institution" model should be added to track the holding institution of a source. This will necessitate moving the "siglum" out of the source title into its own model. 

This means also adding a "holding institution" field to a source. 

The institution model will be based on (but not exactly) the DIAMM 'Archive" model: https://github.com/diamm/diamm/blob/main/diamm/models/data/archive.py

This will also include adding an "institution identifiers" table with several options for indicating the presence of that institution in other authorities -- DIAMM and RISM, in particular, but also probably wikidata and VIAF.

**Comment by dchiller** [comment]
This relates to the series of issues you've created, @ahankinson, but rather than create a meta-issue or discussion, I think it's ok to just discuss this here. 

Ok, so here's what I understand to be the current state of affairs and some of the problems: `title` (current city + current archive + shelfmark), a `siglum` (institution siglum + shelfmark), and a pointer to the `RismSiglum` model (intended to be the "RISM" -- ie. institutional -- siglum). The "RISM" sigla (quotes intentional) used in both the source's `siglum` and `RismSiglum` are not always accurate. The `siglum` and `RismSiglum` fields can be modified independently, as can the title. It's kinda a mess. There's currently no linkage between sources in CantusDB and other catalogs, etc (e.g. RISM, the institution's own record, etc.) 

If I'm understanding this set of issues (1505 - 1509), the goal is to standardize and enhance source identification in the following ways:
- get rid of the `RismSiglum` table and associated fields -- they are not accurate (and also, frankly, not really used)
- create an `Institution` model that contains information (`name`, `siglum`, `city`) on the institutions that hold our sources
- create an `InstitutionIdentifier` model that contains various ID's for the institutions in `Institution`. For example, for the there might be multiple records in Instititution Identifier model that point to the Bodleian (for example, both [BNF cb11930727f](https://catalogue.bnf.fr/ark:/12148/cb11930727f) and [RISM institutions/30001627](https://rism.online/institutions/30001627)
- create a `SourceIdentifier` model that does basically the same thing as `InstitutionIdentifier` but at the source-level. 

_Questions_

1. Is `Institution.siglum` a RISM siglum or a CantusDB siglum?
2. Is `shelfmark` a `SourceIdenfier`? Or maybe we still store that directly on the source itself?

**Comment by ahankinson** [comment]
There is a terminology issue here that’s been known since the migration but hasn’t yet been addressed. See: https://github.com/DDMAL/CantusDB/issues/621

Basically, the word “siglum” can mean “shelfmark” in some musicological circles, but this creates confusion when talking about “RISM sigla”. 

Institution.siglum is a RISM siglum: GB-Ob, D-Mbs, etc.

In an ideal world the Source “siglum” column would be renamed “shelfmark” when the institution component of that is removed and ladder in through its relationship to a holding institution. That’s how it is in DIAMM. But I didn’t want to tackle that just yet, since that’s more a project terminology question, and there’s no technical reason to change it.

Source Identifiers are like institution identifiers, where multiple places may publish a page on the source: wikidata, bnf, RISM, etc. It will operate exactly like the institution identifiers.

**Comment by dchiller** [comment]
> Institution.siglum is a RISM siglum: GB-Ob, D-Mbs, etc.

So, in cases where a source is held by an "institution" without a RISM siglum...I guess this is a place where the current `source.siglum` would hold some kind of identifier to a source's holding location, but that source would not point to an `Institution`.


EDIT: ftr, as I understand it, every holding "institution" of a source in CantusDB **could** have a RISM siglum, I've just heard consistent resistance to making that a requirement.

**Comment by ahankinson** [comment]
That was what we were trying to figure out in the email. I think what we landed on was that sources not held by institutions with a RISM siglum would be “held” by a Cantus institution with its own RISM siglum — CDN-WAcantus or something like that. All sources should have a holding institution, and that should be the only place institution sigla are catalogued.

What the shelfmark is for such sources, however, is still TBD. It could include a geographic indicator, but I have suggested that this isn’t ideal for privacy reasons. That’s a problem for future us at the moment though.

**Comment by dchiller** [comment]
> That was what we were trying to figure out in the email.

And, just realized there's been a whole thread about this going on in an email that I never use :( Ok, reading that now and setting up forwarding lol)

**Comment by annamorphism** [comment]
> > That was what we were trying to figure out in the email.
> 
> And, just realized there's been a whole thread about this going on in an email that I never use :( Ok, reading that now and setting up forwarding lol)

the  double institutional email problems strike again!
