### ISSUE TITLE
Remove "siglum" column on "Browse Chants"?

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1535]
e.g., https://cantusdatabase.org/source/123723/chants/

The "Siglum" column will be the same for every row in the table, and it will be the same as the Source in the sidebar. Given that the table is pretty cramped, it could probably be removed.

**Comment by annamorphism** [comment]
This is a good question. The siglum also appears in some similarly redundant places, like the results for searching a given manuscript, and the full inventory. I think in the case of the full inventory it is there by request, though, since it helps show what you are looking at without scrolling to the top. "Browse chants" may also be incorporating some built-in redundancy in this way--but maybe it's making things cramped for no reason! I will ask.

**Comment by annamorphism** [comment]
Confirmed that this can go!

From Debra:
__That would definitely clean up the page._

_It must be a hold-over from the view (in Drupal) where you see chants from different sources in different searches. I think Django is much more flexible about all of the views, like what you can and don't have to show.__

So let's take this out!
