### ISSUE TITLE
Links to search CI broken 

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1634]
Our link to "Search this chant on CantusIndex" leads to an Access Denied page.
<img width="413" alt="image" src="https://github.com/user-attachments/assets/d8a8f8d3-f6a7-4329-9673-4e52dcafc748">
The URL seems to now be constructed with "master-chants" where ours says "search".

**Comment by dchiller** [comment]
From both a practical (let's be sure that this new url is actually doing the same thing for our purposes as the old url) and principled (ah! you shouldn't just change url's like that without notifying anyone!) reasons, I'm going to send this on to Debra. If the conclusion is that this is a change we need to make on our end, we can do that. But if other sites in the Cantus network use this feature, it might be useful to have this be fixed in Cantus Index.

**Comment by dchiller** [comment]
This has been fixed on the Cantus Index end of things.
