### ISSUE TITLE
Problematic code in views/api.py

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/CantusDB#1638]
https://github.com/DDMAL/CantusDB/blob/develop/django/cantusdb_project/main_app/views/api.py#L394-L441

 - `standardized_chant_values = {keymap[key]: chant_values[key] for key in chant_values}`: `chant_values` is a list of dicts, and you can't use a dict as a key...

```
>>> d = {1:2}
>>> s = {d:3}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'
>>>
```

- `reverse("chant-detail", args=[chant_values["id"]])`: Again, `chant_values` is a list, so it can't be indexed by `id` -- same with the one where it's trying to do it with `source__id`.

**Comment by dchiller** [comment]
Just took a look at this. The code is ok; the problem was in the typing of the function. The `chant_values` argument is actually `dict[str, Union[str, int]]`. For a while there, people were adding type annotations but not using a type checker, so things like this crept in. 

This prompted me to take a look at these functions and I'll do some additional reworking to simplify and because I discovered that we were making non-backwards compatible changes here. (In #1641)

**Comment by dchiller** [comment]
Ooops...accidentally closed now rather than with PR
