### ISSUE TITLE
deleting a user should delete the sources + chants that they have created

### ISSUE THREAD

**Issue by jiwoojeongjj** [DDMAL/CantusDB#197]
likewise, deleting a source should delete the chants inside that source

**Comment by annamorphism** [comment]
not sure i understand this--aren't there situations where you might not need a user account anymore but the content produced by that user is still valuable? Like if a long-standing contributor died, say.

**Comment by jwang44** [comment]
Yes, I'm with Anna on this. It is fine for now if this helps developers test things. But in the long term, we would want to preserve the data even if a user account is deleted. 

I suggest you set them to `PROTECT`, so that a user cannot be deleted when they have sources associated with them. Likewise, a source cannot be deleted when it has chants in it. 

When we're absolutely certain that we want a user/source deleted, we will reassign the associated sources/chants  before the deletion can happen.
