### ISSUE TITLE
Assign a specific user to multiple sources in Django admin

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#217]
In the user-edit page in the Django admin interface, we already have a selector that allows for multi-selecting sources and assigning the user to them. We need to make the selector box wider so that the source titles are not clipped. 

This issue is related to issue #216 , the relationship between the User model and Source model should go both ways.

**Comment by jacobdgm** [comment]
doing a bit of poking around, there does not appear to be an easy way to adjust the width of the select box. And currently, the boxes get narrower when the window gets narrower, which is behavior we probably want to conserve I imagine. 

Suggested workaround: change the string representation of Source objects such that the source's ID precedes its name. The ID is not that long to begin with, and it's unique, which would eliminate the bunch-of-identical-"Budapest, Egyetemi Könyvtár (Univ"-incipits phenomenon currently observed. And if a user needs more information on a source, they can mouse over it to reveal its full name.

**Comment by annamorphism** [comment]
@jacobdgm this functionality is for Debras to assign sources to users, right? And you're proposing the numerical source ID, e.g. "Graz, Universitätsbibliothek, Ms. 211; Antiphonale "Codex Albensis"" becomes "653927"?
It seems to me like a Debra would have to scroll down through a whole lot of potential sources to find the ID for each one of the sources she is trying to assign, mousing over each one, or take down which ones she wants and find their more or less random numbers in the list one by one; either way it would be sort of annoying. Is the space wide enough to fit the RISM siglum (in this case A-Gu 211)?

**Comment by jacobdgm** [comment]
Currently, sources are represented along the lines of `Graz, Universitätsbibliothek, Ms. 211; Antiphonale "Codex Albensis" (653927) `. I was suggesting that we represent them along the lines of `653927 - Graz, Universitätsbibliothek, Ms. 211; Antiphonale "Codex Albensis"`

The space is definitely wide enough for a RISM siglum.

Using the RISM siglum—since it's short, and (I believe) unique—to begin the string representation seems like a much better approach. Something along the lines of `A-Gu 211: Graz, Universitätsbibliothek, Ms. 211; Antiphonale "Codex Albensis" (653927)` would give all the information anyone would need, while providing a unique identifier up front. Good suggestion!
