### ISSUE TITLE
List sources on Indexer Detail page?

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#368]
Currently, on the Indexer List page (http://206.12.93.196/indexers/), the final column in the table lists the number of sources associated with the indexer, and is a hyperlink. Clicking on the link takes me to the relevant Indexer Detail page, which is currently quite sparse and contains no detail about the indexer's sources.

When I initially clicked on one of the "N sources" links, I expected to find out more about the sources that are associated with the indexer. Thus, I suggest we add a section on the Indexer Detail page listing the sources the indexer is associated with. The "sources" column on the indexer list page could then link to that section of the page.

It's worth noting that NewCantus exhibits the same behavior as OldCantus here, but I find this behavior confusing. We should either remove the hyperlink (indexer detail pages can already be accessed from the indexer list page via the link in the "name" column), or add information on associated sources to the Indexer Detail page. Is there any good reason not to add this information to the Detail page?

**Comment by annamorphism** [comment]
I agree this behaviour is strange. If there is going to be a link in the "sources" column it should take us to something with the sources listed. 
Worth noting that the way this is done in Cantus Index does not give a (somewhat redundant) link under "number of chants", but does list all the chants contributed in the user detail page. http://cantusindex.org/user/6490 . A similar approach in the DB would be good (with sources instead of chants).
