### ISSUE TITLE
Production: Indexers and Users not working

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#393]
There are several problems with users and indexers on Production:

**Indexers list page:** no users appear on the list of indexers: http://206.12.93.196/indexers/ . This is working on Staging: http://206.12.88.113/indexers/
![Screen Shot 2022-10-18 at 10 04 44](https://user-images.githubusercontent.com/58090591/196452464-ee7de263-04a6-4a0c-9efb-e25a0a63fc91.png)

**Users list page:** most items on the user list page do not include a name (and thus, do not include a link to the user's detail page): http://206.12.93.196/users/ . This is working on Staging: http://206.12.88.113/users/
![Screen Shot 2022-10-18 at 10 06 53](https://user-images.githubusercontent.com/58090591/196453024-35b01619-8c95-4e54-894b-14f4bfdca9b5.png)

User detail pages seem to work on both Production and Staging. The User List Page issue may have to do with users not having a `full_name` specified. (compare this user detail page on Staging http://206.12.88.113/users/251573, where a name is actually displayed, to the corresponding user detail page on Production http://206.12.93.196/user/251573, where the name is evidently "None")

**Comment by jwang44** [comment]
This has been fixed. Please confirm on production (and close this issue if fixed). The cause of this issue seems to be the "delete all users and load a new user fixture" process. After loading the new fixture, although the users are put back into the database, the many-to-many relationship between sources and users were broken. In the future we should try to avoid loading users in a fixture after everything else has already been created. Otherwise, we may need a script to re-establish those relationships between users and sources.

**Comment by jacobdgm** [comment]
It's working - thanks Junhao!
