### ISSUE TITLE
Periodically save a copy of database in case of disaster

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#395]
Before NewCantus steps up to replace OldCantus, we should set up something to save a copy of the database at regular intervals, just in case disaster strikes and someone deletes all the chants in the database / etc.

**Comment by jacobdgm** [comment]
I'd be interested to hear feedback on how best to implement this, e.g. managing storage on the server vs. keeping copies of the database that cover a good range of time spans.

One possibility is to keep several levels of backups, e.g. daily, weekly, monthly and yearly. Every time we save a new {time period}ly backup, we keep the previous one and delete all older ones at that level, so that at all times we'll have two daily backups on the server, two weekly backups, two monthly and two yearly. Or perhaps that's too complicated? What's best practice here?

**Comment by jackyyzhang03** [comment]
I made a draft PR setting up the cron job inside the postgres container, however, after reading some articles online, it seems that this is not a good practice. Since we probably only want to back up the production database, maybe it makes sense to just ssh into production and add the cron jobs and scripts there manually? We can add something on the wiki, like what we have for the dev_env file.

Interestingly, there appears to be a page on the wiki about backing up Django projects so I'm wondering if we already have a system in place (https://wiki.internal.simssa.ca/wiki/Backups#Backing_up_Django_project_databases).

On a side note, there are some tools such as pg_backrest that appear to be the industry standard way to back up postgres databases. It seems they provide some benefits versus the basic pg_dump, not sure if this is something we want to look into.
