### ISSUE TITLE
Source List page - make searching/filtering more intelligent

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#412]
On OldCantus, searching "Montreal" in the General Search on the sources page gives you the manuscripts in Montreal:

![image](https://user-images.githubusercontent.com/67451875/200409515-e1aa4579-537a-45c2-9b3e-e634fc0b6523.png)

Not so in NewCantus: 
![image](https://user-images.githubusercontent.com/67451875/200409747-17b0ec4b-7b22-46db-b2b8-b0f25c648c7e.png)

Presumably this is because "Montreal" is in the siglum, but not the description itself--the search should really look at both.

**Comment by jacobdgm** [comment]
I'm not seeing "Montreal" in the siglum - does the "Mlr" in "CDN-Mlr" indicate Montreal?

**Comment by jacobdgm** [comment]
This may be a data synchronization issue - looking at the source detail pages on OldCantus and comparing them to the corresponding pages on NewCantus, it appears that "Montreal" is in the description of certain sources in OldCantus but not in NewCantus. Let me try running the script that syncs the sources and see if that helps.

**Comment by ahankinson** [comment]
> ...does the "Mlr" in "CDN-Mlr" indicate Montreal?

The RISM sigla contain all the information about country, city, and holding institution. Each siglum is structured as country code, a dash, an uppercase letter or two indicating the city, and then a lower-case set of letters indicating the holding institution.

`CDN-Mlr` is the siglum for the McLennan Library. The "M" indicates Montreal. `CDN-Mm` is the McGill music faculty library, while `CDN-Mu` is the Université de Montréal music faculty library.

**Comment by annamorphism** [comment]
@jacobdgm actually maybe it's rather that the shelfmark is not getting looked at. "Mlr" gives results but "Montreal" does not. 

It's also a little weird (maybe unavoidable) that this is a string search, so that "Paris" gives all sorts of non-Paris-related things because the word "comparison" is in there somewhere. In combination with omitting some things that *are* in Paris it makes for a pretty unexpected list of sources!

**Comment by jwang44** [comment]
Regarding the search for "Montreal", Cantus doesn't know "M" in sigla means "Montreal" in the current setup. The search operates by a simplistic `icontains` look-up in several relevant fields. In other words, if the letter combination "montreal" doesn't appear in any field, the object won't be returned. 

"Paris" vs. "comparison" is a related issue. It can be solved by adopting a smarter search. Instead of returning anything that contains the letters "paris", it should try to match the whole word, so that something like "This manuscript is in Paris..." will be returned while "comparison between..." will not. 

Ideally, the search should also return the sources where the word "Paris" doesn't appear in any field but is implied in the sigla. We may need to incorporate into Cantus the mapping between geographic locations and their sigla representations.

**Comment by annamorphism** [comment]
@jwang44 a smarter search (maybe one that knows sigla!) would be really good to have. But, every source on CantusDB is required to have both a RISM (or "RISM-like") siglum AND a long-form ID--so everything with a CDN-Mlr... siglum should (I think) already have the magic word Montreal associated with it, because somebody entered it into the "Full manuscript identification" field.

**Comment by lucasmarchd01** [comment]
Checking out this issue... When I search "montreal" I get a list of sources that have Montreal specified in one of the following general search fields: title, siglum, rism_siglum, description, and summary. I believe this has been implemented at some point so I will close the issue for now.
