### ISSUE TITLE
sources list

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#452]
In NewCantus, a non-logged-in user can see 207 sources in the Cantus sources list, which is the same as in OldCantus. But a logged-in editor can see 495 in the list of sources (most of which they are unable to edit). The only way to see anything like that many in OldCantus is under sources-all (which has 506), which is (I thought) an admin-level view only; from the sources list one sees 245. 
That means a typical editor can readily look at hundreds of sources that were previously kept at arms-length from them, even as we are trying to conceal many of the unpublished sources everywhere else. Is this the intent? (Maybe it is, in which case, not an issue.)

**Comment by jacobdgm** [comment]
Currently, edit permissions are slightly different (and simpler) in NewCantus as compared to OldCantus. If a user is logged in, they can see all the sources in the database, whereas users who aren't logged in can only see published sources. The thought was that even if the source was unpublished, someone editing chants in one source might find useful to be able to consult chants in other sources that had not yet been fully indexed and were thus not yet marked as published.

So, I think this is expected behavior.
