### ISSUE TITLE
alphabetical order of sources

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#457]
For some reason, one particular source in Kansas city likes to show up at the top of the sources list, both  http://206.12.88.113/sources/?segment=4063
![image](https://user-images.githubusercontent.com/67451875/205420523-05c9db3a-7c7a-4780-be16-292a8d7ffe6c.png)
 and in the dropdown on "view all chants" 
http://206.12.88.113/chants/?source=710152 
![image](https://user-images.githubusercontent.com/67451875/205420602-531791a2-ea41-4334-8acf-4c3e95faf445.png)

All the other USian sources are in their alphabetical spot, just not this one...

**Comment by jacobdgm** [comment]
So I was able to replicate this locally, and it appears that somehow, the siglum was encoded with a leading space:

```python
>>> from main_app.models import Source
>>> kc = Source.objects.get(id=710152)
>>> kc.siglum
' US-KClbsc M2149.2 .V4 1629'
```

Removing the leading space in the Django shell and then saving causes ordering to work properly on the Source list page; re-adding it causes the ordering issue to happen again.

Curiously, the leading space is evidently not displayed whenever it is rendered on the site. Also, Django appears to strip leading spaces when you press save while editing in the Source Edit view, so this must have been introduced in OldCantus at some point.

**Comment by jacobdgm** [comment]
On both Production and Staging, I edited the source on the Source Edit page and saved without making any changes, and this seems to have resolved the issue. In short, NewCantus is has been ordering its sources properly all along; this is a data issue that occurred because OldCantus doesn't have the same level of data cleaning that NewCantus does. Neat bug; nice catch!
