### ISSUE TITLE
should editors get automatic proofreader access to their own sources?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#491]
It seems weird to me that on sources you (an editor) create, you can always access the Volpiano editor (assuming the source is non-empty!) but you have to be added as an editor to access the proofreading form. 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/67451875/209043248-1a0a8e13-0196-498d-a835-081fddc3ee13.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/67451875/209043188-94b4b649-c1e7-41cc-9692-fd2a6947c28c.png">

If there were something preventing you from proofreading your own source as an intentional part of the workflow, this might be sort of useful (?) but as it is it just adds an extra step to get permissions you should in theory already have.

**Comment by jacobdgm** [comment]
> If there were something preventing you from proofreading your own source as an intentional part of the workflow, this might be sort of useful (?) ...

Hm... Without having thought about it too much, I would think that this is the behavior we want. My impression was that the proofreading step should be completed by a different person, to ensure the person who made the initial transcription for any chant didn't overlook something, is not making any systematic errors, etc.

On OldCantus, are proofreader permissions automatically granted for sources the user creates?

**Comment by annamorphism** [comment]
I think so--in fact I remember there being a mysterious source that got proofread without apparently getting assigned a proofreader.   You're right that it may not in fact be desirable (especially now that "proofreader" is merged into "editor") but it IS what the spreadsheet of permissions indicates. I'll ask about it.

**Comment by jacobdgm** [comment]
Ah! I hadn't seen that Debra made a copy of the first sheet in the spreadsheet and made some modifications. Yes, since that's what the spreadsheet indicates, we should make sure that the creators of sources can proofread those sources.

I left a comment in the spreadsheet with a couple of possible implementations (I think the best approach would be to automatically assign the creator of a source to the proofreader group for that source, rather than having an extra rule to grant the same permissions as being in the proofreader group if the user created the source) - we'll see what Debra has to say.
