### ISSUE TITLE
Certain Genre Detail pages are _very_ slow to load

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#498]
I think the problem is trying to display the "chants by genre" table - for a genre with lots of example chants, e.g. [Antiphon](http://206.12.88.113/genre/122), I've tried loading the page several times and keep getting a 502 error.

**Comment by jacobdgm** [comment]
I see what's going on here: for the genre in question, we're building a tally in Python of the Cantus IDs of all that genre's chants, sorting them by the tally, and then displaying the first hundred of them (assuming the user tried to load page 1). It should be possible to do this all on the database level and load only a hundred results at a time, rather than loading all the data from the database and munging through the Genre's chant set in Python. I will continue to think about this.

down to the nearest hundredth of a second, `get_genre_cantus_ids` (i.e. the algorithm outlined above) takes up the entirety of the runtime of `get_queryset`.

**Comment by jacobdgm** [comment]
I do think that this is going to be a heavy calculation no matter how we slice it. It might make most sense to automatically run this calculation from time to time for each Genre in our database, and cache it in a field on our model.

**Comment by annamorphism** [comment]
Honestly I'm not too concerned about it, since a page containing a list of every antiphon in Cantus DB doesn't seem like a terribly urgent thing to have (and OldCantus doesn't have it.) For that matter, if the genre page were just a page with a description of the genre and maybe a few random examples, it would probably be fine, at least for the time being--and would still be better than what OldCantus has.
