### ISSUE TITLE
Chant Search: keyword/cantus_id field should automatically be populated when searching from search bar

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#515]
The way the search chants page is set up makes it not obvious (in my opinion) what it is you've actually searched for, which is floating off in the upper right while the "keyword" field is blank.

![image](https://user-images.githubusercontent.com/67451875/211895450-63081608-6d7a-49d6-8968-8f4fba2bab7e.png)

On OldCantus it's a little clearer what it is you were looking for, because it's right by the "Full Text Search" words. Or maybe that's just where I'm used to looking for it.

![image](https://user-images.githubusercontent.com/67451875/211895790-a459ad9e-e925-4820-b674-f691b93f36db.png)

**Comment by jacobdgm** [comment]
Ah! this is another one that would be solved by getting rid of the `?search-bar` query parameter and replacing it with `?keyword` (see #516)

**Comment by jacobdgm** [comment]
How exactly do we want this to work?

Currently, in `?search-bar=<search_term>`, if `search_term` contains any non-letter characters, we search for all chants/sequences whose `cantus_id` is equal to `search_term` and return them - this is exactly the same behavior as `?cantus_id=<search_term>`.

However, in `?search-bar=<search_term>`, if `search_term` contains only letters, we search for all chants/sequences whose standard-spelling fulltext begins with `search_term`. This is different from `?keyword=<search_term>&operation=starts_with`, which searches standard-spelling fulltext, ms-spelling fulltext, and incipit.

I feel that in an ideal world, whenever a person makes a search from the search bar, we would use `?keyword=` or `?cantus_id=` as appropriate, and not use a `?search_bar` query parameter at all (this would also have the effect of the search term appearing in the corresponding field in the form). If we implement it this way, _are we happy with searching all three text fields for the search term rather than searching just the standard-spelling field as we currently do?_

A further question: currently, in the `ajax_search_bar` function (which displays search results when you type into the search bar without pressing enter), we only search chants' incipits. We also search only for chants, and not for sequences. This means that if a user types something into the search bar and sees a certain collection of chants displayed, they might get an entirely different set of search results once they press enter. _Is this desired/acceptable behavior?_

**Comment by annamorphism** [comment]
My initial thought is that searching all three text fields is probably an improvement over the current behaviour, since it means people don't have to mentally "standardize" the spelling to get results. I'll think about whether there's any cases where this would be a bad thing. 

I'll have to think about the Ajax search bar. My instinct is that the difference in results is not a problem, though.

**Comment by jacobdgm** [comment]
One consideration: My guess is that the Ajax search bar searches only the incipit in order for it to return results quickly (and that OldCantus searches the same field for the same reason), and if we searched multiple fields here, the user would need to wait longer before results are displayed.

**Comment by annamorphism** [comment]
I was thinking the same--that there's a trade-off between completeness and getting some results quickly. I don't think that's too weird for the user (it's sort of like an autocomplete for chant...)

**Comment by jacobdgm** [comment]
Notes for future fixing of this: Django has a built in `get_initial` method that could be useful here.

**Comment by jacobdgm** [comment]
Currently on OldCantus, no matter what you search for in the search bar, it ends up in the "incipit" field on the main form. This means that if you search for a Cantus ID and press `enter`, OldCantus will search for the ID in the incipit field. So NewCantus's system is already better than OldCantus's, in that you can see a list of chants with matching Cantus IDs when you search for something involving numbers!

But it would certainly be even better if we auto-populated the keyword/cantusID field (depending on the presence of numbers) when a user uses the search bar.

Assigning a label of "enhancement" for this reason.
