### ISSUE TITLE
Work on optimizing Chant Search page

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#519]
We should implement an option to search only chant incipits, rather than chants' full texts (the latter of which takes a long time, as noted in #513)

It should be an option on the main chant page rather than an entirely new page, to prevent proliferation of chant search pages, a thing that seems to have occurred in OldCantus (see #421)

One thing to think of: how would this interact with "contains" vs "starts with"? Maybe all we need to do is search only incipits when the user has selected "starts with", set "starts with" as the default option , and not bother adding a new incipit-vs-fulltext field?

**Comment by annamorphism** [comment]
If I understand correctly, you're saying 1) by default the search bar would be "starts with" and not "contains"--I like this, because *most* of the time people are probably looking for a chant that starts a certain way and not for all chants containing a certain word, even if the latter situation does also come up. Then 2) this search only needs to look at the incipits, since the word(s) a chant starts with will by definition also be what the incipit starts with.  If that is what you are saying, then I agree!

(The only potential weird results I foresee would be cases were the first few words of a chant are missing, when there could be a mismatch between the incipit and the full text on the page--but I think it wouldn't upset anyone to include these among the search results if the incipit has the words in question.)

**Comment by jacobdgm** [comment]
It feels very natural to set up #361 while solving this issue. One question @annamorphism - can you imagine a situation ever arising where a user searches for many words (perhaps 6 or 8) occurring at the beginning of the chant? If we only store the first 5 words as an incipit, then no results would show up if a user searches for 6 or more words.

**Comment by annamorphism** [comment]
It's possible, but I don't think it's very common--probably less common than trying to look for a mid-chant word using the incipit search. I think in both cases redirecting users to a full-text search, or some sort of instructive message ( "Your search had no results. Try searching only the first five words of the chant.") would be good solutions.

**Comment by jacobdgm** [comment]
Update: at lab meeting, we came to the conclusion that we should not try to implement incipit search, and instead work to optimize full-text search.

**Comment by jacobdgm** [comment]
While this could probably be optimized further, this page has felt quite performant over the past few months IMO. Closing - we can always reopen if necessary.
