### ISSUE TITLE
chant-search breaks on partial words

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#528]
Searching, say, "etia", or "wi", gives no results under "contains"--though, oddly enough, both give something under "starts with". 
"tiam" gives a few results, but only because there are chants with "e]tiam" in them (or something similiar.) 
 
In OldCantus searching partial words works just fine, whether searching incipits or full texts and starts or contains.

**Comment by annamorphism** [comment]
Actually this seems to be related to #419--despite "wi" having no results, "willibald" gives us "willibalde/i"--though not "willibaldus". So sometimes partial words give results and sometimes not.

**Comment by jacobdgm** [comment]
Somehow, I didn't get around to trying to recreate this bug until now. This bug is really odd!

http://206.12.93.196/chant-search/?op=starts_with&keyword=etia gives 4 results, while both
http://206.12.93.196/chant-search/?op=contains&keyword=etia and
http://206.12.93.196/chant-search/?search_bar=etia give 0 results.

**Comment by jacobdgm** [comment]
Further:

http://206.12.93.196/chant-search/?search_bar=tia gives 3 results (this is unexpected, because we'd expect it to catch at least the 4 results from `?search_bar=etia`)
http://206.12.93.196/chant-search/?op=contains&keyword=tia gives 7 results
http://206.12.93.196/chant-search/?op=starts_with&keyword=tia gives 0 results (this is to be expected, though, I think?)

**Comment by annamorphism** [comment]
> Further:
> 
> http://206.12.93.196/chant-search/?search_bar=tia gives 3 results (this is unexpected, because we'd expect it to catch at least the 4 results from `?search_bar=etia`)

Didn't ?search_bar give 0 before? At any rate, it IS unexpected, since tons of words contain "gratia" or "justitia". however, the three chants listed all have a "word" consisting of just "tia" or "-tia" because of various missing syllables. So it may be that search_bar assumes a preceding space/hyphen or something. 

>http://206.12.93.196/chant-search/?op=contains&keyword=tia gives 7 results 

This link shows 3 results for me, so I'm guessing there is a logged-in/non-logged-in thing at play here to

>http://206.12.93.196/chant-search/?op=starts_with&keyword=tia gives 0 results (this is to be expected, though, I think?)
Yes, I think this is right.

**Comment by jacobdgm** [comment]
We get ~30000 results for `contains` `keyword=tia` currently on Production.

for `search_bar` searches, it should only match things that _begin_ with `tia`, and not those that contain `tia` later in the text (i.e. it should be exactly the same as a `starts_with` `keyword` search iirc)

@annamorphism, can you take a look at this to see whether it's properly fixed now?

**Comment by jacobdgm** [comment]
I maintain that this is now fixed. Closing.
