### ISSUE TITLE
Apply database indexing to speed up search

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#530]
We can apply `db_index=True` to several of the fields in our models to speed up searches.

Question for the musicologists - on the chant search page, we have options to filter by Office, Genre, Cantus ID, Mode, Feast, and Position. Are users more or less likely to want to filter their results by any of these? (i.e. we can set up indices that will speed up filtering of search results, but each index we create will take up memory, so we should only create indices for fields users will commonly want to search by). My guess is that **Office, Genre, Cantus ID and Feast will be particularly useful** to filter by, whereas **Position and (perhaps) Mode are less likely** to be used. Is my guess accurate, @annamorphism?

**Comment by annamorphism** [comment]
I'm not sure. I confess that I rarely use these filters on OldCantus, having gotten set in my habits of ordering and re-ordering search results and looking at concordances or Cantus Index pages when necessary, so I'm also not so sure how necessary it is to speed up the filtering of results.
I also don't know to what degree users actually use the filters for questions that could not be answered otherwise, vs. for more common questions that could also be answered in other ways.  For example,  position is actually a somewhat useful filter, since one cannot order the "position" column in the search results (which has a variety of number/letter mixtures in it); ditto Feast. On the other hand, people probably want to differentiate between chant genres more often than than they care about something being Matins Antiphon 3.3-- but it's also quite trivial to answer this by either ordering one's search results once received, or by looking at the IDs, or by using Cantus Index for this particular task, rather than filtering Cantus DB.  
So I am not sure if, in practice, Position is a more commonly used filter than Genre. 

I think in order of usefulness one would want to filter by feast, Position/Genre/Office (people will use these as a group much of the time, particularly in combination with Feast), Cantus ID, and Mode (only because there usually aren't too many modes for a given chant of interest, and they are orderable).   But I don't think speeding up filtering is that high a priority, personally.

I will think on it and see if I agree with myself on Monday...

**Comment by jacobdgm** [comment]
okay, this is good to know - thanks!

Note to self (and perhaps to others): One thought was to make indexes for our table of chants based on whether or not their source is published. But doing a bit of investigating, only about 1/10 of the chants come from unpublished sources, so this won't make all that much of a difference...
