### ISSUE TITLE
Chant Proofread page missing Edit Syllabification link

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#573]
The Chant Proofread page is missing a link to open the Edit Syllabification popup, a link which is present on the Edit page. While OldCantus is also missing an Edit Syllabification link on the proofread page, this appears to be a bug rather than a feature.

This is a bit of missing functionality that is important to have. In order to resolve this issue, we need to add an Edit Syllabification to the proofread page.

## Previous version of the post

Compare http://206.12.88.113/proofread-chant/669030?pk=669065&folio=007v to http://206.12.88.113/edit-chants/669030?pk=669065&folio=007v. I haven't checked whether OldCantus leaves this link off of the proofread page, but this seems like an important oversight.

**Comment by annamorphism** [comment]
I don't seem to have the relevant permissions on staging to see the links provided...

In OldCantus you can edit the syllabification via edit-volpiano but not /node/blah/edit; c.f. 
![image](https://user-images.githubusercontent.com/67451875/222546022-684169d2-020d-4dcd-84a3-d926c1f1703b.png)
![image](https://user-images.githubusercontent.com/67451875/222546155-ac3871e0-f965-4b59-80f7-3644b42710cd.png)

Highly annoying in my opinion, especially since there are different permissions and paths involved to get to each of those places...

**Comment by jacobdgm** [comment]
I have permissions to access https://cantus.uwaterloo.ca/proofread/699578, and I don't see an Edit Syllabification link anywhere.

If this is a feature we should close this issue. If it's a bug, we should fix it. @annamorphism, is this worth checking in with Debra about the intended functionality?

**Comment by annamorphism** [comment]
It seems to me that editing syllabification should be a past of the proofreading process, and that we do want it here. The OldCantus pages don't work exactly the same way, but the one that is closer to the proofread functionalities (edit-volpiano) is the one where you can edit syllabification. So we should fix this.
