### ISSUE TITLE
Full Inventory Page, Bower segment: sequences out of order

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#583]
discovered on staging, http://206.12.88.113/index/?source=123906. Seems to be caused by some folios not having leading zeroes. Sequences, as far as I understand, can be ordered by `s_sequence` alone, rather than by `folio` and then by `c_sequence` (sequences don't have a c_sequence - only chants do)

**Comment by ahankinson** [comment]
You're looking for "natural sort" (as opposed to "ASCIIbetical" sort). Technically your database is sorting by the ASCII code of the leading digit. 

There are a number of ways to solve this. The "easiest" is to post-sort your results in Python. There are some packages out there that does it, but the easiest is just to left-pad the string with zeros out to a fixed number to create a fixed-length string, and then sort on that.

000001
000045
000123

Since the zeros always sort first, this will end up in the correct order.

On the other hand the "correct" way is to implement this as a new collation in Postgres for fields that will need to be sorted this way. https://blog.testdouble.com/posts/2022-12-12-pg-natural-sorting/

NB: You will probably also find this problem when sorting by shelfmarks. For that you would need to identify numeric components of the string and left-pad those.

**Comment by jacobdgm** [comment]
I think that natural sort by `folio` and then by `s_sequence` (i.e. the sequence notation Calvin Bower used) would solve this problem. But also, since `s_sequence` orders sequences in a manuscript rather than on a folio, the tweak made in #585 also works. Since Calvin Bower used his own idiosyncratic system for assigning "sequence numbers" to the sequences he found in the MSs he looked at, even if we implement "natural sort" in one way or another, things will end up displayed out of their intended order.

I don't know that it's worth trying to unpick all the situations where this occurs - unless someone (i.e. Debra) identifies natural sort as an important enhancement, ASCII sort is probably sufficient.
