### ISSUE TITLE
Feast Detail Page: why are we displaying so many frequent chants?

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#596]
On [this Feast Detail page](https://cantus.uwaterloo.ca/feast/1581), we're currently displaying _all_ the chants associated with the feast. OldCantus only [shows 50 chants](https://cantus.uwaterloo.ca/feast/1581). The same is true for the "Sources containing this feast" list. We should change the behavior of NewCantus to match OldCantus.

Considerations:
- This is mostly driven by a desire to be consistent - if we say we're displaying the most frequent chants, we should display only the most frequent chants. But in fixing this, we'll likely prevent pages from taking too long to load, and prevent them from becoming too long (see, e.g., the sluggish and lengthy http://206.12.93.196/feast/2211)
- OldCantus has buttons at the bottom of each table allowing the user to "LOAD MORE" - we could probably accomplish the same with pagination links. We'd have to have two different paginations, one for each table, which is a little bit tricky to implement, but we've already done it elsewhere.

**Comment by jacobdgm** [comment]
assigning @lucasmarchd01 because you've recently handled multiple paginations.

I don't think this is important enough to prevent us from launching NewCantus (either "soft" or "full"), and I feel the "low priority" label is still justified, but we should fix this eventually.

**Comment by lucasmarchd01** [comment]
After implementing pagination on the feast-detail page, I realized that this wouldn't actually solve the loading time issues for this page. This is because we fetch information for all of the cantus_ids in the feast (count, incipit, genre) and zip them to be used in the template. Pagination would not solve the issue since we still need to fetch this information before paginating. It might be worth considering setting up a model for cantus_id so that we can optimize the number of queries on this page and likely on other pages as well.
