### ISSUE TITLE
OldCantus has a bunch of new pages

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#632]
OldCantus has several new pages I haven't seen before: https://cantus.uwaterloo.ca/url-aliases, https://cantus.uwaterloo.ca/feasts-import, https://cantus.uwaterloo.ca/feasts-update, https://cantus.uwaterloo.ca/renumber and https://cantus.uwaterloo.ca/publish-chants.

These pages are accessible through Admin Navigation section in the footer.

This issue is going to be fleshed out soon!

**Comment by annamorphism** [comment]
I found these recently too! I am not sure what they are supposed to do (I don't think they work at the moment??)

**Comment by fujinaga** [comment]
Check with Debra.

On May 10, 2023, at 2:02 PM, Anna ***@***.***> wrote:



I found these recently too! I am not sure what they are supposed to do (I don't think they work at the moment??)

**Comment by annamorphism** [comment]
Sent an email, will report back.

**Comment by annamorphism** [comment]
Recording our email conversation here for posterity. Debra is in quotation marks; my own comments are in square brackets.
https://cantus.uwaterloo.ca/url-aliases, https://cantus.uwaterloo.ca/feasts-import, https://cantus.uwaterloo.ca/feasts-update, https://cantus.uwaterloo.ca/renumber and https://cantus.uwaterloo.ca/publish-chants.

https://cantus.uwaterloo.ca/renumber
"This is supposed to renumber the "sequence numbers" of chants on a single folio side or page after the insertion or deletion of one or more chants. For example, if there are 25 items on a page, and I have to insert 1 at the top that was missed in the initial indexing, I would have to open all 25 other records to change the sequence numbers. This seemed to me like something a computer should be able to do. I haven't tried it though, since Jan made it earlier this winter, told me about it, but then did the changing of the numbers I needed to test that it worked."
[[Conclusion: this would be nice to have but is a recent development and doesn't seem to work properly. Could be a feature request for NewCantus, to be done differently. I don't think anyone will notice its absence.]]

https://cantus.uwaterloo.ca/publish-chants
"I used to use this a lot when I was editing chants, since (apparently) the way I was entering the records was causing them to become unpublished while I was working on them, and as I edited, the number of records in the database diminished. They returned after about a day, but it was annoying to me that they disappeared (since I might have wanted to re-edit them in the same session, or users might have been using the site at the same time and then not see them). Jan had wanted me to open the records through another portal but that was more clicks for me and I frequently forgot because I have other things on my mind (and I'm old). You will need to make the new site a bit more foolproof for me -- though I'm not completely a dolt when it comes to computer applications, at least I don't think so."
[[I'm guessing this was happening through not going through the "correct" proofread/edit form, and I think that aspect of the interface is solved in NewCantus. I think everything is currently published by default (which seems like it might have problems of its own), so I'm not sure if this tool is still useful. ]]

https://cantus.uwaterloo.ca/url-aliases,
"Actually, I know nothing about this one"
[[My guess is this is part of the node-to-chant URL conversion, which still show up in OldCantus in mysterious ways. If so it's probably not necessary in NewCantus. ]]

https://cantus.uwaterloo.ca/feasts-import
https://cantus.uwaterloo.ca/feasts-update
"Please don't.
I had asked at one point to have a single feast list for both resources (Database and Index) because for each new feast I have to add it twice, once in each site. I try hard now to keep the Cantus Index feast list as clean as possible, but the wiki-nature of it means that it's a tough job. It was a poor idea of mine to request to have the two lists be the same -- that wasn't really what I wanted. I wanted one clean list. Lesson learned."
[[At some point it may be useful to revisit this problem and work out a better way of doing it, but it seems unnecessary to replicate it in NewCantus if it is such a 'poor idea.']]

"Jacob mentioned "Update CSV file". I don't think I have this, unless it's the Image link one? I don't know how to use that. Jennifer and I always thought that adding image links to the records was something the Developer should do, so we never learned how to do it. (We were encouraged to take care of it ourselves, but we have always had higher-level tasks to accomplish in limited time.)"
[[Sounds like another NewCantus Feature Request--much like the re-numbering, it's something that is there, but even the few people who have access to it don't know how to use it, even though it would be very useful to have.]]

**Comment by jacobdgm** [comment]
Attempting to distill this further:
https://cantus.uwaterloo.ca/renumber - this might be nice to have eventually, but it's not necessary
https://cantus.uwaterloo.ca/publish-chants - not necessary
https://cantus.uwaterloo.ca/url-aliases - we have a [plan](https://github.com/DDMAL/CantusDB/issues/563) to handle the node vs. chant/source/etc., so we should be able to ignore this one
https://cantus.uwaterloo.ca/feasts-import, https://cantus.uwaterloo.ca/feasts-update - not necessary

...which indicates, I think, that the ultimate distillation is "we don't need to implement anything new"

finally, some thoughts re: https://cantus.uwaterloo.ca/publish-chants - I'm further guessing that this was an artifact of OldCantus's two-dimensional visible-published system, which we've simplified into a one-dimensional published-vs-unpublished system, which is assigned to sources rather than to chants. I've not noticed chants or sources becoming unpublished as they are edited/proofread, so I think we can safely ignore this one.

**Comment by jacobdgm** [comment]
It's worth noting that the screenshot Debra included in one of her emails includes several links I've never seen (e.g. add indexer, etc.) - perhaps these things are available only to people with Debra-level permissions, and I don't have them?

I'll expand on this comment, find and attach the screenshot, etc. either tomorrow or sometime soon.

**Comment by annamorphism** [comment]
My Debra-level access also has "add indexer":

<img width="266" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/33adf9f3-afd2-4bcb-8686-49281e352df1">

**Comment by annamorphism** [comment]
And here is Debra's screenshot, along with her comments about what is useful (Y is regularly used in OldCantus, X is not necessary, XX is actively unhelpful,  Y? is possibly-useful unknown functionalities, and ?? are complete unknowns).

<img width="291" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/c34941b9-0081-4f8a-854f-0ca0dfc569ae">


"Add Indexer" won't be necessary in a world where indexers and users are the same thing--it's a way for Debras to create Indexer entities who can be credited on a source page. So it's very useful in OldCantus but not needed in the New.

**Comment by jacobdgm** [comment]
@annamorphism, do the bunch of issues you opened last week cover everything in this issue? Are we fine to close this one? Are we fine to close #633?

**Comment by annamorphism** [comment]
I haven't actually spun these into their own issues, because I think everything in it falls under either "not necessary to replicate" or "nice feature to create in the future maybe". Closing this, will refer back to it if it turns out some piece of it needs implementing after all.
