### ISSUE TITLE
We have to renumber Articles to match IDs on OldCantus

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#675]
On OldCantus, we have an article at `/article/712586`. The same article has url `/article/36` on NewCantus. So, in general, article url's copied from OldCantus don't seem like they will resolve correctly.

**Comment by jacobdgm** [comment]
When I set up the articles app about a year ago, I remember it being decided that we would not preserve article ids from OldCantus to New. @fujinaga, would you like me/someone to go through and manually renumber these, for backwards compatibility? There are about 40 of them.

**Comment by fujinaga** [comment]
Yes, you can ask Marisa or you can do them yourself.

Thank you.

On Jun 7, 2023, at 05:42, Jacob deGroot-Maggetti ***@***.***> wrote:

﻿

When I set up the articles app about a year ago, I remember it being decided that we would not preserve article ids from OldCantus to New. @fujinaga<https://github.com/fujinaga>, would you like me/someone to go through and manually renumber these, for backwards compatibility? There are about 40 of them.

**Comment by jacobdgm** [comment]
So it turns out this is a more important issue than it first appears, mostly because /node/ urls can point to articles (see #563).

Also, this is a thing it doesn't make sense to fix immediately, because if we renumber news articles on staging or production, then run the sync-data scripts locally and copy the database onto staging/production, the articles will be reset to their numbering that was on the local machine. Let's wait until we've done our data-syncing dry run, then update article numbers, then make sure the renumbering is propagated to all installations of the CantusDB app (local installs, staging, and production).

Finally, it looks like this is a task either I or @lucasmarchd01 will have to do by hand - I looked briefly into renumbering articles in the Admin panel this morning with @PythonSemicolon, and it looks like the process will be non-trivial (i.e. it can't simply be done in the admin panel without changing some settings)

**Comment by jacobdgm** [comment]
Now that we have /node/ redirects set up, we need to attend to this.

**Comment by jacobdgm** [comment]
I finished this yesterday! Articles are properly renumbered on both staging and production!
