### ISSUE TITLE
We should change the path to the `Fields and Content Description` page

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#677]
Flagging a discrepancy between Old and NewCantus...note the Jump to Source and Articles widgets at `/field-descriptions`. Also note that OldCantus hosts this page at `/description` rather than `/field-descriptions`. Also note that on NewCantus, the `Manuscript Reading (MS Spelling)` has "TO DO" (this section is populated in OldCantus.

OldCantus

<img width="1020" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/754c4546-5be0-4607-ac56-b99b47951c19">

NewCantus

<img width="1233" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/07790b59-09a3-42d6-8974-592566a05edc">

**Comment by jacobdgm** [comment]
I've updated the content of these pages on Staging and on Production. These are flat pages, saved in the database, so if we're going to update the path from `field-descriptions` to `descriptions`, we need to change the `<a>` tag in `base.html`, and then manually change the path associated with the page when we roll the changed code out to staging and to production.

In order to update the content of these, I basically copied and pasted the code from the relevant OldCantus page. But NB in case others need to do this - a bunch of the urls pointed to pages within cantus.uwaterloo.ca, so I had to tweak these to use local paths (also note that several other pages have different paths too - OC uses `office` where NC uses `offices`, OC uses `page/637811` where we use `about/id-numbers/`, etc.)

**Comment by jacobdgm** [comment]
Also, we should change the styling of `<code>` blocks on our site - the magenta that's currently there looks terrible! Guessing this is a bootstrap default.

**Comment by jacobdgm** [comment]
And I think it's fine that these sidebar links are displayed here. Since this page is a flatpage, and the homepage is a flatpage, it will be a non-trivial to remove on this page without removing it from the homepage/etc.

**Comment by jacobdgm** [comment]
I've updated the [to do] that used to be in the content of the page, on Production. We still need to change this path.
