### ISSUE TITLE
`/edit-chants/{id}` leads to `404` when source has no chants

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#711]
A source created that has as of yet no chants has a `404` error when attempting to reach `/edit-chants/{source_id}`.

This url can be accessed by clicking the "Edit chants (Fulltext & Volpiano Editor)" link on the home page or the source page.

NewCantus: 
<img width="1431" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/915afa5d-b2f9-4d35-9878-f7cafbdfb9d5">

OldCantus (accessed at `/edit-volpiano/{source_id}`:
<img width="1440" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/5cec9bc7-85a0-4378-bd74-a76e0770af2e">

**Comment by jacobdgm** [comment]
To fix this, we need to do two things (or maybe just one of them):

- Make sure this link is not displayed when there are no chants to edit (I thought we already fixed this? we should check again)
- make sure that this page can load even if there are no chants (and if we implement this, maybe we don't need to do the first of these. Even better, we should check what OldCantus does in terms of displaying links, and then copy that)

**Comment by annamorphism** [comment]
NewCantus does seem to display the link, as @dchiller noted, on the my sources page; this is in parallel with what OldCantus does, where the "Fulltext and Volpiano editor" option always displays, even for empty sources. 
(I don't *mind* the idea of not having it show for empty things, if that is easier to implement than loading the page--there's nothing you can do in the full-text editor if there are no chants. But OldCantus does let you go look at the form, as in the screenshot above.)

**Comment by jacobdgm** [comment]
The fastest way to fix this, I think, will be to hide links to the page.

The more robust fix will be to have the page be able to load even if it doesn't have chants, _and_ hide links to the page. This will account for situations where people have bookmarked Edit Chants pages, as well as for the end of the chant-delete process (otherwise, it's not clear where we should redirect users afterwards - maybe to the source detail page?), as well as any links we may have somehow missed.

**Comment by jacobdgm** [comment]
> The more robust fix will be to have the page be able to load even if it doesn't have chants, and hide links to the page. This will account for situations where people have bookmarked Edit Chants pages, as well as for the end of the chant-delete process (otherwise, it's not clear where we should redirect users afterwards - maybe to the source detail page?), as well as any links we may have somehow missed.

Talking through this a bit more with @lucasmarchd01, we've had some thoughts. From a user-experience point of view, instead of sometimes hiding edit-chants links (in the situation where the source has no chants), it would probably be best to always show these links, and when the user tries to visit the page, display a message explaining that there are no chants available to edit, and give them a link to create a new chant.
- This way, no user is confused when they can't find an edit-chants link where they expect to find one.
- It would also more closely match where/how these links are currently displayed on OldCantus

I'm not 100% certain this is the best approach - we should probably check in with Debra about what she'd prefer. In any case, this is low-priority for the time being.
