### ISSUE TITLE
`Images` link for first two manuscripts in "Browse Chants" page lead to a page that never loads

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#712]
To reproduce:

- Go to "Browse Chants" page;
- Click on the "Images" link for either A-Gu 29 or A-Gu 30;
- A new tab opens, but the url is weird and the site never loads.

Demo (New vs. Old comparison):

https://github.com/DDMAL/CantusDB/assets/83373378/fa8da2fc-0d77-4e7b-bb9a-73a384936b68

I've clicked on random other manuscript images and they all load fine. From my casual random selection, it seems to be just these two that are badly behaved.

**Comment by annamorphism** [comment]
That weird URL shows up elsewhere on the internet, so I'm assuming the library changed it at some point; I think it was still floating around on OldCantus last October, so it should go away once the data is updated (but will be worth checking.)
OldCantus links to the images at literature.at : http://www.literature.at/viewer.alo?objid=1138&page=9&viewmode=fullscreen&rotate=&scale=1
It would actually be much better to link to the university's images:  https://unipub.uni-graz.at/obvugrscript/content/pageview/6789708 , both because the URL is less ugly and also because the literature.at ones are in a completely bonkers order (which will be relevant to serving them on CU: @dchiller take note!) But maybe that is a problem for Cantus to solve and not DDMAL!

**Comment by jacobdgm** [comment]
We can't do too much about other sites not loading well, but if there are different urls, this is a data issue that we can expect to be resolved once we sync the data from OldCantus to New.

@annamorphism, I'm assigning you to this, in case you want to change the urls for these sources as you suggested (either do it on OldCantus in the next few days so we can sync from there, or wait for the full switchover and make the change both on Staging and Production). Please close this issue once you're done (or whenever you feel it's appropriate).

**Comment by jacobdgm** [comment]
As there is nothing for NewCantus developers to do about this issue, I'm closing it.
