### ISSUE TITLE
When merging Indexers and Users from OldCantus, we should preserve original Indexer IDs rather than user IDs

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#714]
When we merged the indexer and user models last year, where a person had both an indexer object and a user account, we kept the existing user ID and added some indexer-relevant information to the user object, including the person's old ID as an indexer.

Since you can get to an Indexer detail page via a /node/ URL in OldCantus (see #563), we should renumber users so they are identified by their original Indexer ID.

**Comment by jacobdgm** [comment]
@PythonSemicolon: could we set up #563 do this without renumbering users? For the indexer check, we could just use `User.objects.get(old_indexer_id=pk)` rather than `User.objects.get(id=pk)`, couldn't we?

**Comment by jacobdgm** [comment]
If we renumber users in this way, we should also set up a redirect in case someone tries to access a user page via the user's old ID. But this may not be necessary, if we adopt the approach to #563 outlined in my previous comment.

**Comment by PythonSemicolon** [comment]
> @PythonSemicolon: could we set up #563 do this without renumbering users? For the indexer check, we could just use `User.objects.get(old_indexer_id=pk)` rather than `User.objects.get(id=pk)`, couldn't we?

My initial though was that this couldn't work due to conflicts such as [this](http://206.12.88.113/chant/251425) and [this](http://206.12.88.113/user/251425) sharing the same ID. However, in theory it should be possible since the conflicts only occur between NewCantus User IDs and OldCantus node IDs (meaning that as long as we don't search for the former, there can only ever be at most one match). In the case of the previously mentioned match, the [ID from the /node/ path](https://cantus.uwaterloo.ca/node/706860) won't match any other nodes, we just have to look for it in the different attribute as mentioned. Will give this a go.

**Comment by PythonSemicolon** [comment]
The fix seems to work @jacobdgm! I begin by checking if there is a user whose `old_indexer_id` matches the node ID. If there is, that user's page is returned; otherwise, the other four tables (chant, source, sequence, article) are checked, and finally a 404 is returned following that.

**Comment by jacobdgm** [comment]
sounds great - much better than changing all our users' IDs!

Take note, @lucasmarchd01 - looks like we won't need to change this aspect of the data syncing process.

Thanks all around!

**Comment by lucasmarchd01** [comment]
Sounds good, thanks!
