### ISSUE TITLE
If NewCantus is open and inactive for 5+ minutes, 502 errors ensue

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#813]
Steps:

1. Open a NewCantus tab on the Home Page;
2. Do something else for at least five minutes;
3. Back to NewCantus, select any source from the "Jump to Source" drop-down menu;
4. This will likely lead to a 502 Bad Gateway error. If it doesn't the first time, click on another source.

I've tried this four times, and so far the 502 error happens every time.

When it does happen, it takes a while for NewCantus to warm up again. Clicking on different sources produces the same error. What has worked for me so far is clicking on a series of innocuous and easy-to-load pages, such as things under the "About" header; after a few clicks, I can generally come back to the sources menu and select one successfully. (I'm going to give this a priority: medium tag; I hope it's not too brash.)

**Comment by annamorphism** [comment]
Thanks for looking into this, @JoyfulGen --I'd noticed a surprising number of 502 but hadn't managed to replicate them consistently!

**Comment by jacobdgm** [comment]
I noticed 502s on certain Source Detail pages, but only on Production and never on Staging or locally - I don't know why this should happen.

While I was investigating this issue, I noticed a optimization we could be making on many of our pages that we weren't at the time. #834 implements this optimization, and testing locally, I found it cut load times for a Source Detail page roughly in half. I doubt it will fully solve this issue, but might alleviate things somewhat.

@kqct, are there any tests we can run on production to try to identify a bottleneck that might be causing this?

**Comment by ahankinson** [comment]
502s generally happen when the front-end server (nginx) can't contact the upstream application server within a set amount of time. This typically has a number of causes, some of which may be found in combination:

1. Your upstream server cannot handle the amount of traffic coming to it. If someone's request takes a long time to process, your app server will stop accepting requests until it's returned.
2. Your front-end server has too small a timeout set. If requests take too long to return, the frontend server may close the connection. Sometimes this results in 504 Timeout error, but this depends on your configuration.
3. Your upstream app server has too small a timeout set. For example, gunicorn may have a timeout set, after which it closes the connection.

What can you do to fix this?

1. Make your responses as fast as possible. Your site will pause while slow queries are processed, so the faster a query is returned, the more traffic your site can handle.
2. Increase the number of workers. In the DIAMM gunicorn process handler we use 5 (https://github.com/diamm/diamm/blob/master/gunicorn_start.sh). I see you do as well.
3. Use django's caching. https://docs.djangoproject.com/en/4.2/topics/cache/
4. Use nginx's caching, https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/
5. Increase timeouts
6. Deploy multiple instances of the app and load balance them. (This can get really tricky really quickly, though, since you have to ensure logged-in users get access to the same session across requests). 
7. Check docker resource constraints for both the app server and the database server. Move away from docker onto the "bare" machine if necessary.

I also noticed that the Cantus Production machine is way under-specced. (2VCPU, 3GB RAM... that's really not enough). You would be better to create a new Ubuntu machine and deploy directly to bare metal, but at the very least a new machine with an up-to-date Ubuntu, more resources, and a fresh docker install would go a long way to fixing this.

**Comment by jacobdgm** [comment]
> I also noticed that the Cantus Production machine is way under-specced. (2VCPU, 3GB RAM... that's really not enough). You would be better to create a new Ubuntu machine and deploy directly to bare metal, but at the very least a new machine with an up-to-date Ubuntu, more resources, and a fresh docker install would go a long way to fixing this.

I wonder if these were initially set up as under-specced while NewCantus was under development, with the intention of them being expanded once we were approaching the full launch.

@fujinaga, does it make sense to ask Jennifer for permission to use a bit more of her allocation? If yes, should I send this email, or would you prefer to do it yourself? @kqct, is this a thing you can easily change if we decide it's the right thing to do?

**Comment by fujinaga** [comment]
Did you guys get an account? If not, ask @ahankinson to get a bigger instance.

**Comment by jacobdgm** [comment]
> Did you guys get an account? If not, ask @ahankinson to get a bigger instance.

I have an account on her allocation, and I believe @kqct has one too.

To make sure: you're suggesting we just make a bigger instance on Jennifer's allocation ourselves, and not bother asking Jennifer about it. Is this correct?

**Comment by kqct** [comment]
I don't believe I ever ended up with access to the instance -- I know it was talked about, but I don't think we ever moved forward with it.

re: the allocation issue, it's absolutely possible to change the amount of resources allocated to a VM. The Alliance has a couple of different profiles that might work better -- I can find a list for them if you'd like

**Comment by ahankinson** [comment]
I've set up a new machine and am waiting for @jacobdgm to get me his details to connect to it. I can add others as well -- send me your desired username and public SSH key by e-mail and I'll set that up.

**Comment by fujinaga** [comment]
Correct.

On Jul 13, 2023, at 08:54, Jacob deGroot-Maggetti ***@***.***> wrote:

﻿

Did you guys get an account? If not, ask @ahankinson<https://github.com/ahankinson> to get a bigger instance.

I have an account on her allocation, and I believe @kqct<https://github.com/kqct> has one too.

To make sure: you're suggesting we just make a bigger instance on Jennifer's allocation ourselves, and not bother asking Jennifer about it. Is this correct?

**Comment by ahankinson** [comment]
Browsing around the site, it seems much better now. The source pages load quite quickly, and I haven't had a 502 error.

**Comment by jacobdgm** [comment]
@JoyfulGen, how do you feel about the site now - any 502s in the past week? If things are feeling sufficiently fast and reliable, can you go ahead and close this issue?

**Comment by annamorphism** [comment]
@jacobdgm I got an email today from somebody who has been getting 502s when attempting to add new chants--though seemingly only sometimes, since he said it worked fine in the morning but not later in the day. Not sure what is going on there.

**Comment by JoyfulGen** [comment]
@jacobdgm I haven't encountered 502s in a while (in fact, I've never seen the custom 502 page and I'm quite disappointed), but I can't speak to the adding of new chants that @annamorphism mentioned.

**Comment by jacobdgm** [comment]
Okay, I'm going to close this issue and create a new one about the Chant Create page. Thanks for your thoughts/feedback, @annamorphism and @JoyfulGen!
