### ISSUE TITLE
NewCantus is not set up to use https://

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#860]
NewCantus is not set up to use https://. Once we switch the DNS settings for cantusdatabase.org (which really has to happen no later than tomorrow), anyone who tries to visit https://cantusdatabase.org will get a warning message in their browser.

Currently, trying to navigate to http://cantusdatabase.org redirects to https://cantusdatabase.org. So anyone who has bookmarked anything on OldCantus over the past several years will be affected by this.

Thanks, @dchiller, for catching this!

I'm not sure what's involved with getting a certificate and configuring this etc. Tagging @timothydereuse because this is urgent, as @kqct is in a not-ideal timezone.

**Comment by ahankinson** [comment]
I suggest using Let's Encrypt. https://letsencrypt.org
The Lego client for it is really good. https://github.com/go-acme/lego

You'll want to set up a cron job to auto-renew the certificates since they expire every three months, but can be automatically renewed.

I don't know who does your DNS for cantusdatabase.org, but I've had the most success with the DNS challenge method. The HTTP challenge method is also possible, but is sometimes a bit finnicky.

**Comment by kqct** [comment]
Given that the DNS records for cantusdatabase.org are managed directly through the registrar, we aren't currently able to use the DNS challenge method. If that ever changes, I think it would be a good idea to move to DNS, but we're stuck with HTTP for now (which also means we can't preconfigure it).

**Comment by jacobdgm** [comment]
This is complete! Huge thanks to @kqct for helping to sort this out! Closing.
