### ISSUE TITLE
Cantus IDs sometimes get merged; Cantus Index has an API to show which Cantus ID have been merged

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#877]
In an email from Jan:

>  In our CI form, we have the option to set Cantus IDs that need to be renamed across all databases. https://cantusindex.org/merged 
> This renaming process can be done immediately upon submitting the CI form (after calling some URL in CD), or alternatively, you can set up a regular cron job to periodically check JSON https://cantusindex.org/json-merged-chants and rename the Cantus IDs in CD. I'm not certain which approach you would prefer.

We should probably check in with Debra first, but this is a thing we should probably implement before too long.

**Comment by jacobdgm** [comment]
Sounds like Debra wants/needs this updated soon. Increasing the priority.

**Comment by jacobdgm** [comment]
A couple of weeks ago, I looked into the json-merged-chants API and https://cantusindex.org/merged and found some unusual things, including:
- duplicate mappings: for example, old a00556 maps to new a00555a twice.
- places where one Cantus ID maps to itself: for example, 008276:06
- places where one Cantus ID maps to multiple new Cantus IDs: for example, old 008276f maps to both 008276:06 and 008276:07

I asked Jan and Debra about this, and based on the response from Jan, it seems that the API lists a record of all merges that ever happened on CantusIndex. In instances where one old Cantus ID maps to multiple updated Cantus IDs, it seems that one merge occurred, then users continued to add chants with the old Cantus ID, and then a second merge occurred changing these new chants to a different updated Cantus ID.

Jan suggested that whenever we run whatever script we come up with, we keep track of the index/id of the last mapping we performed, and only apply mappings that follow this one.

I'll need time to investigate further and think about good approaches to handling this; maybe we can discuss it at lab meeting.

**Comment by jacobdgm** [comment]
Another thought. Jan suggested that he could add the ID of the merge event in the API. It might make more sense to ask that a timestamp be attached to each record. That way, if we run a cron job every day (say), we can filter the JSON objects by checking their timestamp is after the last time we ran the cron job. And when we do an initial run of this script, we can only apply updates that occurred since we did the final data migration from OldCantus to New.

**Comment by jacobdgm** [comment]
Update, based on the Zoom call with Debra we just finished:

**We should set this up so that CantusIndex can trigger a Cantus ID update in CantusDB, so that IDs are updated right away.** We shouldn't worry about the CantusIndex API - it keeps a record of past merges, but **we will never need to go back in this history and re-apply a merge that occurred in the past.** No one has applied any Cantus ID merges since before we did the final OC-NC data sync, so again, we don't need to worry about applying past merges.

**Comment by annamorphism** [comment]
Was emailing with Debra about merging chants and got a reply including "...if it's in the Cantus Database, we would want the renumbering/merging feature working so that if we change it in the Cantus Index it will also change it in NewCantus. I haven't heard if this is functional yet. It should (if I have a wish list) go up in the priority list because there are some other changes I need to make and I have held off so that I don't have to manually change NewCantus."
Bumping this to be on a front burner.

**Comment by jacobdgm** [comment]
So, one possible implementation for this:
- we ask Jan to update https://cantusindex.org/json-merged-chants to include a timestamp for each mapping
- we create an endpoint to which PATCH (or PUT? POST? I think PATCH is correct here) requests can be sent. A valid request would be a json object of the form `{"old-cantus-id": "updated-cantus-id"}`.
- When CI wants to signal that a Cantus ID should be updated/remapped they:
  - update the json-merged-chants API to list this update
  - send a PATCH request to our new endpoint
- When we receive a PATCH request to this endpoint, we check the json-merged-chants API to see whether this new update is listed among the mappings there, and if its timestamp is within the last 60 minutes. If it is, we perform the update.

Other implementations could involve:
- only accepting PATCH requests from CI's IP address
- giving CI a developer key, and we only accept PATCH requests if they have a valid key. I think this is best practice, and Django (or at least Django Rest Framework, which we don't yet use) almost certainly provides this functionality. I don't have any experience setting this up, though. @dchiller, CU uses Django Rest Framework, doesn't it?

**Comment by dchiller** [comment]
> CU uses Django Rest Framework, doesn't it?

Yes, but the only place we allow non-GET requests is behind our admin authentication, so we don't have any experience with keys.

**Comment by jacobdgm** [comment]
Talking with @alastair, we decided that the best approach would be to work with the current system. It will be necessary to ask him to attach a timestamp to each "transaction" in the /json-merged-chants API, so that we can keep track of which transactions have already been applied and only apply new transactions. We can set up a cron job to visit the API every day/hour/sometime, and apply any new mappings. I'll email him next week to request this.

**Comment by dchiller** [comment]
I think this last approach makes sense!

**Comment by jacobdgm** [comment]
Having thought about this a bit over the weekend, I realize why progress on this issue has ground to a halt: In early November, we asked Jan to add a timestamp to each item in the array at https://cantusindex.org/json-merged-chants, and we're still waiting for this to be added. I just sent an email to Jan making sure this is still on his radar.

Going to mark this issue as "on hold" - we'll remove this on-hold label once the ball is back in our court.

**Comment by jacobdgm** [comment]
https://cantusindex.org/json-merged-chants!

**Comment by lucasmarchd01** [comment]
In `cantusindex.py`, we are using the new domain cantusindex.uwaterloo.ca which is still currently under development. There are some APIs such as this one (`json-merged-chants`) that are still only available on the old site. Jan has suggested that we use the APIs from cantusindex.uwaterloo.ca and continue using hyperlinks to the old site. They will have identical content in the future. I think in that case we should put this on hold until the `json-merged-chants` API is available on cantusindex.uwaterloo.ca (I will make an issue on https://github.com/dact-chant/cantus-index)

The other option is to temporarily use the old domain for this particular endpoint until it's added to cantusindex.uwaterloo.ca, since this is a high-priority feature Debra wants to have.

**Comment by lucasmarchd01** [comment]
> It will be necessary to ask him to attach a timestamp to each "transaction" in the /json-merged-chants API, so that we can keep track of which transactions have already been applied and only apply new transactions. 

Linking #1158 here

We need a way internally to track which transactions were applied last. If we set up a management command that will run under a cron job, there isn't an easy way to determine when the last time the command was run. There are a couple ways I can think of doing this:
- Keep a record of the timestamp of the last successfully processed transaction. This could be stored somewhere in a text file
- Create a model to store the timestamp of the last run of a command. Something like this:
```
class CommandRunTimestamp(models.Model):
    command_name = models.CharField(max_length=255, unique=True)
    last_run = models.DateTimeField()

    def __str__(self):
        return f"{self.command_name} last run at {self.last_run}"
```

**Comment by dchiller** [comment]
This is an honest question, because the chances that there are nuance of this that I am not getting are high:

Is it true that we need to keep track of when the last command was run? Bracketing out the efficiency of this approach, could we just, let's say on the daily:
- get the list of the merged CantusIDs
- check the database for the old CantusID
- wherever we find an old CantusID, change it to the new one

If no ID's have been merged between the last run of this theoretical command and today, then this would check all the CantusID's in CantusDB and find that we don't have any "old" ID's because all the "old" ones have already been mapped to "new" ones. So we just design an idempotent command. 

EXCEPT: we don't do any integrity checks on Cantus ID's, I don't think, so there is no restriction on someone adding an "old" ID after we've already run the transformation on that particular Cantus ID. So in fact, if the above doesn't present any problems, it may in fact be preferable to trying to determine the timestamp of the most recent run.

**Comment by dchiller** [comment]
The other thing I just thought of is that Jan didn't actually add a timestamp...he added a date. Which means we potentially won't know whether we have applied a change... was the merge on Cantus Index made on the given date before our cron job runs or was it made after our cron job (and therefore needs to be run the next time we run our cron job).

**Comment by lucasmarchd01** [comment]
>  get the list of the merged CantusIDs
    check the database for the old CantusID
    wherever we find an old CantusID, change it to the new one

You know, now that you mention it, this does seem like a much simpler solution. I think I was getting bogged down in a lot of the earlier discussion of the issue. My worry was the complexity of this problem becoming larger and larger as more merge events happen. I'm having flashbacks to #1368 where updating many chants with a management command runs into resource problems and doesn't complete its run correctly. But it's true that we don't have to worry so much about the old changes since they will be skipped if the old CantusID doesn't exist anymore. 

I'll work on a solution that doesn't involve using a new model or the timestamps on the API. I think this will be more reliable.

**Comment by dchiller** [comment]
> I'm having flashbacks to #1368 where updating many chants with a management command runs into resource problems and doesn't complete its run correctly.

This seems like a fair concern. I don't have a sense of how many chants are affected, so it may not work if its tons and tons.

**Comment by lucasmarchd01** [comment]
I suppose we can use `.update()` in this case instead of `.save()`, which should improve the efficiency?

**Comment by annamorphism** [comment]
for a sense of scale, 2381 Cantus IDs have been merged since the beginning of record keeping. Usually it's really not very many per year, although 2021 was a big year for merges (over 2000!).  They tend to happen in binges, where several will happen on one day and then not a lot for a long period of time; so you'd want to make sure you catch (say) all the June 1 2024 ones, but if (because of the date not being a timestamp) you missed a few on June 1 itself, the next run would likely catch all the remaining ones (as there wouldn't be too many new ones.)

**Comment by lucasmarchd01** [comment]
Thanks @annamorphism! In that case, if we're performing this command under a cron job, say, every week, then I don't think the magnitude of chants that could change will reach a number that we should be concerned about.

**Comment by ahankinson** [comment]
A good concept here (if you don't already know it) is "idempotent" -- that is, you can run the same command multiple times and it will always produce the same result. For example, HTTP calls like POST, PUT, and PATCH are supposed to be idempotent, where you can repeat the same request many times and the result on the server will be the same.

https://en.wikipedia.org/wiki/Idempotence#Computer_science_meaning

**Comment by lucasmarchd01** [comment]
Re-opening until we have the cron job set up on ansible

**Comment by lucasmarchd01** [comment]
With https://github.com/dact-chant/ansible.cantus-db/pull/36, It should be ready to go!
