### ISSUE TITLE
Question (not sassy): why are the Office/Mass abbreviations hyperlinked?

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/CantusDB#985]
This is a question for @jacobdgm and also perhaps @annamorphism. On this page https://cantusdatabase.org/offices/, all the abbreviations are hyperlinked. But if you click on any of those links, you're brought to a page that specifies the description of the abbreviation, but contains no other information. That description is in the original table in the first place, so the hyperlink isn't bringing the user to anything new. And it's sort of strange to click on a hyperlink and then have nothing effectively happen... Would it therefore be possible to just remove them? Or are they there for future adding of things?

**Comment by jacobdgm** [comment]
As I've been working in our templates over the past year, I've been adding hyperlinks to Office and Genre Detail pages wherever we display a chant's office or genre, for increased connectivity; I've asked Debra, and she said to go ahead and add such links whenever I come across them.

I'm of the mind that if we have Office and Genre Detail pages, we should link to these pages whenever we can. Note that OldCantus does a similar thing: https://cantus.uwaterloo.ca/office/ includes links to a bunch of vestigal Office Detail pages. https://cantus.uwaterloo.ca/genre behaves similarly, but the Genre Detail pages contain a list of chants by genre.

Ultimately, I think a better solution could be to simply add a list of chants to the Genre and Office detail pages. (we had this on the Genre detail page at one point, but we removed it because the page was taking too long to load. I have a sense now of how we can add this list and make it load quickly, so maybe this is the time to reimplement this)

**Comment by jacobdgm** [comment]
I just opened #988 and #989, suggesting that we add information to Office/Genre Detail pages so they don't look so barren when users follow hyperlinks to them.
