### ISSUE TITLE
Displaying chants/sequences without sources

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#992]
From @jacobdgm

> Also - we may want to check in with Debra about whether to display chants/sequences without sources. In OC, there was a boolean `visible` property (sources could definitely have it, and possibly chants/sequences could too), which we got rid of, rolling everything into our `published`. Since all our visibility-related logic is based on a chant/sequence's source, we may not want to default to displaying chants to everyone on the grounds that they don't belong to an unpublished source.

_Originally posted by @jacobdgm in https://github.com/DDMAL/CantusDB/pull/990#discussion_r1296349020_

**Comment by jacobdgm** [comment]
@annamorphism - guessing you'll say we should check with Debra, but perhaps you already have a strong sense of what we should do here. Thoughts?

My gut instinct: if a chant/sequence doesn't have a source, it's not in publishable form, and we should not display it to unauthenticated users.

**Comment by annamorphism** [comment]
I don't fully understand the issue--do you have an example of a source-less chant?

**Comment by annamorphism** [comment]
Hang on, I found one--https://cantusdatabase.org/sequence/623263 leads to a 500. 

Here it is on OldCantus: https://cantus.uwaterloo.ca/sequence/623263 . 
It's kind of bizarre--it has a RISM ID, but there's not actually a source associated with that ID, so you can't tell what else is in there, and it doesn't show up in concordances (or even in the admin list of sources on OldCantus).  Weirder still, I can't figure out what source it's supposed to be--"SN-SBfm" should correspond to a country+library but I don't know which. 
On the other hand https://cantus.uwaterloo.ca/sequence/631313 (also broken in NewCantus) has a siglum that belongs to something I can find (Bibliotheque de l'Arsenal 608, a 14th c. missal from Poissy.)

Anyway, so: 
-We should not display chants/sequences without sources, because they are displeasing and broken
-Some sort of way to turn these up (for me and Debra et al) would be helpful, to figure out how many of these there are. I suspect most of them are sequences that got imported into the Bower database from some file with blanks in required fields, but maybe there are some /chant objects as well. 
-Is it possible to "attach"errant chants and sequences onto a source? Normally you can't make chants without starting from a source, but clearly it has occasionally happened and we need a way to fix it when it has.

**Comment by annamorphism** [comment]
update: there are also a few chant objects that do this. e.g. https://cantus.uwaterloo.ca/chant/688442 (broken on NewCantus: https://cantusdatabase.org/chant/688442). I have no idea what this particular chant is supposed to be part of, or how it even got made....

**Comment by jacobdgm** [comment]
> Some sort of way to turn these up (for me and Debra et al) would be helpful, to figure out how many of these there are.

It should not be possible to create sourceless chants/sequences, so I expect no new ones to be added. And for the time being, I can tell you which chants/sequences have no source:

```python
>>> sourceless_chants = Chant.objects.filter(source__isnull=True)
>>> sourceless_chants.count()
29
>>> for chant in sourceless_chants:
...     print(chant.id)
... 
688274
688443
688444
688446
688448
688449
688451
688453
688454
688456
691964
691965
691966
691969
691971
691972
691973
691974
714271
688272
688273
688442
688450
688275
688445
688447
688452
688455
1001628
>>> sourceless_sequences = Sequence.objects.filter(source__isnull=True)
>>> sourceless_sequences.count()
427
>>> for seq in sourceless_sequences:
...     print(seq.id)
... 
631249
631225
631235
631259
631269
631283
631293
631303
631313
631328
631333
631353
631358
621015
621016
635550
635552
635553
635557
635558
635560
635562
635566
635567
635572
635571
635576
635579
635581
635585
635586
635587
635589
635591
635592
635593
622366
622370
622371
622373
622374
622376
622378
622379
622381
622383
622384
622386
622419
622389
622390
622394
622395
622398
622400
622401
622405
622406
622409
622411
622415
622416
622418
622421
622423
622424
622426
623058
623059
623060
623063
623064
623065
623068
623069
623070
623073
623074
623075
623078
623079
623080
623083
623084
623085
623272
623270
623259
623261
623263
623264
623266
623268
623269
623274
623275
623276
623279
623280
623281
623284
623285
623286
623289
623290
623292
623294
623295
627619
627623
627624
627629
627634
627636
627641
627644
623759
627645
631234
631390
631240
631241
631245
631264
631267
631273
625113
631274
631287
631288
631294
631298
631300
631306
631308
631312
631318
631319
631323
631325
631331
631337
631338
631343
631344
631348
631350
631356
631362
631375
631383
631384
631391
631393
631395
631371
627247
627248
631396
627251
627252
627253
631397
627256
627257
627258
627261
627271
627266
627270
627274
627275
627276
627280
627281
627633
631080
631081
627615
627616
627617
627620
627621
627622
627625
627626
627627
627630
627631
627632
627635
627637
627638
627640
627642
627643
627646
631363
631364
631365
631366
631367
631380
631368
631369
631373
631370
631372
631374
631381
631382
631388
631389
631076
631077
631078
631079
631223
631224
631226
631227
631229
631231
631232
631233
631236
631237
631238
631239
631242
631243
631244
631246
631250
631251
631252
631253
631256
631257
631258
631260
631262
631263
631265
631266
631268
631270
631271
631272
631275
631279
631286
631281
631282
631284
631285
631289
631290
631291
631292
631295
631296
631297
631299
631301
631302
631304
631305
631307
631309
631310
631311
631314
631315
631316
631317
631320
631321
631322
631324
631326
631327
631329
631330
631332
631334
631335
631336
631339
631340
631341
631342
631345
631346
631347
631349
631351
631352
631354
631355
631357
631359
631360
631361
631376
631377
631378
631379
631385
631386
631387
631392
631394
635551
635554
635555
635556
635559
635561
635563
635564
635565
635568
635569
635570
635575
635573
635574
635577
635578
635580
635582
635583
635584
635588
635590
622382
622367
622369
622372
622387
622391
622392
622397
622402
622403
622412
622413
622417
623061
623066
623071
623076
623086
623267
623262
623278
623288
623293
627250
627255
627260
627262
627264
627265
627268
627272
627273
627278
623513
627269
627249
627254
627259
627263
627267
627277
627279
627618
627628
627639
621014
621017
622393
622368
622375
622377
622380
622385
622388
622396
622399
622404
622407
622408
622410
622414
622420
622422
622425
623062
623067
623072
623077
623081
623082
623087
623271
623273
623260
623265
623277
623282
623283
623287
623291
631228
631230
631247
631248
631254
631255
631261
631276
631277
631278
631280
```

**Comment by jacobdgm** [comment]
...notice the chant with ID 1001628? It must have been created in NewCantus. #996

**Comment by annamorphism** [comment]
just reiterating from our meeting:
-sourceless chants should not be viewable to non-logged-in users.
-Somebody will eventually clean these up by inputting the sources for the relevant chants, which can be done via the Admin interface (admittedly in a somewhat tedious fashion, since each individual chant has to be updated)

**Comment by lucasmarchd01** [comment]
I have updated the code in #1005 so that chants and sequences without a source are not displayed on the site other than in the admin area. We can close this issue or leave it open until we know all of the objects Jacob gathered have been dealt with or assigned a source.
